### ISSUE TITLE
Some archived feedback I don't remember if sent

### ISSUE THREAD

**Issue by birbilis** [NetLogo/NetLogo#1189] opened 2016-10-31 14:50 UTC
Cleaning up some backup of mine, I found NetLogo_Birbilis_feedback_20100923.txt file with the following content. Sharing it here since I don't remember if I had sent that feedback (together with other e-mail discussion with Seth most probably), or was TODO / for elaborating. 

If anyone can spot issues in NetLogo still existing from those shorthand notes, please log them to issue tracker and comment with respective links below. If you need some clarification(s) for some text from below I can try to remember what exactly it was about (if it's not clear)

---

doc for sort should also write sort list-of-agents after sort agentset

doc for sort should have "If the input..." and "Any list items..." parts in one paragraph (and should say something there that the 2nd phrase excempts the case of a list-of-agents)

doc for sort should also say how agents that are links are sorted (not only speak about turtles and patches)

any? and empty? should be interchangeable and same goes for count? and length? - I don't see why need separate mental model for words/lists and agentsets (apart from the fact that the agentset contents aren't ordered). Unless its for optimization (although I guess the compiler could be clever enough to optimize such stuff) or for helping the parser

source editor should right-trim source lines (remove trailing spaces even after comments)

is-...-set? need to also be available with special names for <breed>, not only turtle/link/patch/agent (btw a bit inconsistent to write agentset, but turtle-set, patch-set etc. although understandable since agentset term is ancestor of all)

turtle-set/patch-set/link-set need to also be available with special names for <breed>. If you implement inheritance (see relevant suggestion below) it would work with descendents too

there should be an alternative tick form as (tick number) equivalent to tick-advance number

using { output-show word "Vetoed to " ([master] of myself) } works ok but { output-show word "Vetoed to " [master] of myself } doesn't (shows two lines, first saying "Vetoed to " and second just writing e.g. (connector 5) : (connector 5)

type and output-type should optionally accept any number of params (write ...) and (output-write ...)

type (applies to output-type too) doc should say "Its output will not include quotes around strings unlike write. "

doc says at write:  "Its output will also includes quotes". Should write "include" instead

doc says at write "output value, which can be a number, string, list, boolean, or nobody" but not saying anything about the kind of value (apart from speaking about quotes in strings) at print/show/type (btw, I'd also expect some comments/examples on how lists are shown [with brackets? and also about sublists])

doc at <breed>-own says "If you specify a breed instead of "turtles", only turtles of that breed have the listed variables. (More than one breed may list the same variable.)" but the compiler doesn't allow it (did you mean to say that if "turtles-own" is used instead all breeds get that variable?
I'd prefer to see somekind of inheritance when defining breeds (e.g. breed [mammals mammal]  breed [cats cat] of mammals) where common properties would be defined/shared at the ancestor breed). You'd internally implement possibly with a class equivalence function where when one asked for all mammals, the equivalent(mammals,dogs) and equivalent(mammals,cats) check would return true (I guess now you use = when you construct agentset given a breed-related query). BTW Java's "Class" class has more proper names for inheritance checking methods (see its API - has separate checking for descendence and equivalence etc.). BTW could implement multiple-inheritance using say "breed [mules mule] of [horses donkeys]" (supposing mule was indeed a superset of both races) 

allow more instances of the same view (like viewports / numbered and named) and in 3D too (e.g. in a car racing you have mirrors or you may have a zoomed out map of a big world etc.). If could have transparent patches then one could have overlapping views too (like a small semi-tranparent map of a world at one of its corners)

allow cloning GUI items (clone would be instantiated at x+ofs,y+ofs)

allow multiple (numbered/named) output areas (e.g. one might want to show instructions at other place than resuls or have separate result areas etc.)

alt down at observer/commandinput history dropdown and at any dropdownlist on the GUI should drop the list (as on Windows)

not consistent to allow COLOR for both links and turtles (whereas patches have pcolor) but not allow to have same-named custom variables at different breeds (may have parser issues if changed [pitty], but if can't would expect lcolor for links for consistency)

mouse-zcor (3D mouse / see DirectInput on Windows)

optional to params checked at runtime given as 2nd optional list at TO0
also empty list to mean any num of params, accessed via a paramslist (all params) or maybe an optionalparamslist with just the optional ones (I prefer to always have a paramslist function for any proc, even if it doesn't have optional params)

right-clicking output area should show "Clear" action to clear its current text

pressing F1 at 1st char of row with just spaces or at empty row (or right click / Quick Help) says "could not be found in NetLogo Dictionary...etc.". Should open dictionary directly in that case (that is when search token is of empty length). Same happens if one selects Look up in dictionary from Help menu when in Interface tab

pressing F1 at other than the leftmost pos of a row with just spaces doesn't offer to show help dialog! (same does when right-clicking at other than the leftmost pos on the row of spaces and selecting QuickHelp - doesn't open dictionary)

there's no do-while command that would execute a block once then evaluate condition for loop (for completness it would be also nice to have until and do-until)

at any? says see also all instead of all?

all? takes a reporter - I think any? should optionally take a reporter too

edit / select all doesn't select all widgets (is only for text editor?)

right-clicking empty area of GUI should have select all option and if any selection also have an Unselect All

should say maybe deselect intead of unselect?

from Planarity game/model: NetLogo does not have a primitive which detects whether two links intersect.  To do the detection, the code uses the SUBTRACT-HEADINGS primitive and some math.
Intersecting Links Example -- has sample code for finding the point where two links intersect

add edit/format menu action to format source (shown only when in source pane) and at context popup of source editor

rename Quick Help to Definition - holding down ctrl over a command at code editor or at the event script dialog (or at command center) should highlight it and clicking on it should scroll to its definition in the procedures tab (or to its documentation if its a primitive). Need to make the event script window floating [with z order to keep it always on top] instead of modal - try JInternalFrame maybe or if there's related option at JDialog

at script editor should have questionmark button at top-right before the [x] to show help on how to use the dialog - same could be at the main netlogo windown

double-clicking yellow error bar should scroll the error line (the highlighted one) into view (JScrollPane or the edit box has such function I think). Same should do at script dialog for completness

colorchart image not shown at .../docs/programming.html#colors

when navigating with arrow keys to pos after [ or ] one should be able to press CTRL+DOWN and CTRL+UP respectively to go to the respective matching ] or [ (same should do at ctrl+click on a [ or ]). Similar should do for parentheses 

let/set should accept list of variable names as 1st parameter to define/init and set value of multiple variables respectively (to same expression for all - avoiding thus the recalculation of the expression or having to use local variable to 1st keep the expression, plus gaining in conciseness

apart from link-length, link-heading and link-set should also have <breed>-length, <breed>-heading and <breed>-set for undirected/directed link breeds

can-move? distance 
 Reports true if the calling turtle can move distance in the direction it is facing without violating the topology; reports false otherwise. 
 It is equivalent to: 
 patch-ahead distance != nobody
Is this equivalent indeed? I'd expect can-move? to check all the path till that distance for missing patches (no corridor to the target patch), whereas patch-ahead isn't expected to do such thing

extensions should be able to define help files for the QuickHelp feature (e.g. pressing F1 on profiler:start finds nothing now) and have a sample on how to build correctly the help file (with correct style and bookmarks)

link-set {and patch-set respectively} say:
"List inputs to LINK-SET {PATCH-SET} must only contain link {patch}, link {patch} agentset, or list elements.  The list ... contained ... which is NOT a turtle {...} or turtle {...} agentset". It should not have "NOT" in that error message when you've indeed mistakenly say given a turtle in that set

why can't one place a report inside an ask?

```
to-report adapt-to [master]
  let connector self
   
  ask my-rods [
    let minlen min-length
    let maxlen max-length
    ask other-end [
      let dist (distance connector)
      ifelse dist < minlen [
        output-show "Push"
        report 0
      ][
        ifelse dist > maxlen [
          output-show "Pull"
          report 1
        ][
          output-show "Resize"
          report 2
        ]
      ]=
    ]
  ]
end

```

error while connector 0 running REPORT in procedure ADAPT-TO
  called by procedure PROPAGATE
  called by procedure MOVE
  called by procedure GO
REPORT must be immediately inside a TO-REPORT
(halted running of start)

> org.nlogo.nvm.EngineException: REPORT must be immediately inside a TO-REPORT
>  at org.nlogo.prim._asm_adaptto_report_12.perform(:1)
>  at org.nlogo.nvm.Context.runExclusive(Context.java:132)
>  at org.nlogo.nvm.ExclusiveJob.run(ExclusiveJob.java:69)
>  at org.nlogo.nvm.Context.runExclusiveJob(Context.java:183)
>  at org.nlogo.prim._asm_adaptto_ask_6.perform(:1)
>  at org.nlogo.nvm.Context.runExclusive(Context.java:132)
>  at org.nlogo.nvm.ExclusiveJob.run(ExclusiveJob.java:69)
>  at org.nlogo.nvm.Context.runExclusiveJob(Context.java:183)
>  at org.nlogo.prim._asm_adaptto_ask_1.perform(:1)
>  at org.nlogo.nvm.Context.callReporterProcedure(Context.java:237)
>  at org.nlogo.prim._asm_propagate_if_3.perform(:3)
>  at org.nlogo.nvm.Context.runExclusive(Context.java:132)
>  at org.nlogo.nvm.ExclusiveJob.run(ExclusiveJob.java:69)
>  at org.nlogo.nvm.Context.runExclusiveJob(Context.java:183)
>  at org.nlogo.prim._asm_propagate_ask_0.perform(:1)
>  at org.nlogo.nvm.Context.runExclusive(Context.java:132)
>  at org.nlogo.nvm.ExclusiveJob.run(ExclusiveJob.java:69)
>  at org.nlogo.nvm.Context.runExclusiveJob(Context.java:183)
>  at org.nlogo.prim._asm_go_ask_5.perform(:1)
>  at org.nlogo.nvm.Context.stepConcurrent(Context.java:95)
>  at org.nlogo.nvm.ConcurrentJob.step(ConcurrentJob.java:95)
>  at org.nlogo.job.JobThread.runPrimaryJobs(JobThread.java:194)
>  at org.nlogo.job.JobThread.run(JobThread.java:117)
> 
> NetLogo 4.1.1
> main: org.nlogo.app.App$AppFrame
> thread: JobThread
> Java HotSpot(TM) Server VM 1.6.0_21 (Sun Microsystems Inc.; 1.6.0_21-b06)
> operating system: Windows 7 6.1 (x86 processor)
> Scala version 2.8.0.r17517-b20090416021636
> JOGL: (3D View not initialized)
> OpenGL Graphics: (3D View not initialized)
> Path: .URL: https://subversion.assembla.com/svn/nlogo/trunk:46689:46696
> model: PushPullRotate
> 
> 09:51:30.088 Events$SwitchedTabsEvent (org.nlogo.app.Tabs) AWT-EventQueue-0
> 09:51:30.074 Events$RuntimeErrorEvent (org.nlogo.app.App$7) AWT-EventQueue-0
> 09:51:30.064 Events$JobRemovedEvent (org.nlogo.app.App$7) JobThread
> 09:51:30.059 Events$OutputEvent (org.nlogo.app.App$7) AWT-EventQueue-0
> 09:51:30.058 Events$InterfaceGlobalEvent (org.nlogo.window.ChooserWidget) AWT-EventQueue-0
> 09:51:30.058 Events$PeriodicUpdateEvent (org.nlogo.app.App$7) AWT-EventQueue-0
> 09:51:29.132 Events$InterfaceGlobalEvent (org.nlogo.window.ChooserWidget) AWT-EventQueue-0
> 09:51:29.132 Events$PeriodicUpdateEvent (org.nlogo.app.App$7) AWT-EventQueue-0
> 09:51:28.932 Events$InterfaceGlobalEvent (org.nlogo.window.ChooserWidget) AWT-EventQueue-0
> 09:51:28.932 Events$PeriodicUpdateEvent (org.nlogo.app.App$7) AWT-EventQueue-0
> 

some a bit far-off ones:
- could have "TO breed:action" and TO [breed1 breed2 ...]:action" (could even not have a : and use a space since actions can't have same name as breeds). Compiler could then check that you don't run a command that is allowed only for certain breeds to other ones (not sure if consistent with hatching from one breed another one though)
- could also have x:[cmds] and [x y]:[cmds] as alternative to ASK and x:[reporter] as alternative to [reporter] of x (see previous one - could have "." instead of ":" for similarity to other languages)

**Comment by mrerrormessage** [comment] 2016-10-31 16:00
Thanks for reporting. I'll work on verifying, categorizing and splitting these out into separate bugs/enhancements in the next few days.

**Comment by mrerrormessage** [comment] 2016-11-09 20:03
First, thanks so much for passing these ideas along. This list alone contains more good feedback than we often receive in a month.
I think many of these ideas are really great ideas. Some of them I've created issues for, others I've asked for clarification on, and some I've said I don't think apply to more recent versions of NetLogo.

There's another category that these issues fall into which is being too time-consuming to implement easily while not being an important enough of a change to warrant the time involved.
As we only have one full-time developer on NetLogo at the moment (myself), we don't have much bandwidth for major changes.
My assessment of the cost of the issue is based on my experience with the NetLogo codebase, while my assement of the "importance" of a change is largely subjective.
If you think I'm missing something, please let me know and we can continue to discuss.

Since I've created a separate issue for many of the items, feel free to close this issue once you've had your questions / comments answered to your satisfaction. If I don't hear back, I may close the issue in a week or two.

> doc for sort should also write sort list-of-agents after sort agentset

The documentation for sort already has `list` as one of the inputs and details what happens if the list contains an agent. I don't think separately enumerating `list-of-agents` is necessary.

> doc for sort should have "If the input..." and "Any list items..." parts in one paragraph (and should say something there that the 2nd phrase excempts the case of a list-of-agents)
> doc for sort should also say how agents that are links are sorted (not only speak about turtles and patches)

I've created [this issue](https://github.com/NetLogo/NetLogo/issues/1203) to capture concerns about the documentation of `sort` if you have more thoughts to add, please leave a comment there.

> any? and empty? should be interchangeable and same goes for count? and length? - I don't see why need separate mental model for words/lists and agentsets (apart from the fact that the agentset contents aren't ordered). Unless its for optimization (although I guess the c
ompiler could be clever enough to optimize such stuff) or for helping the parser

Issue created [here](https://github.com/NetLogo/NetLogo/issues/1204) for further discussion. I think this idea has some real potential, although I'm unsure what we'll end up deciding on it.

> source editor should right-trim source lines (remove trailing spaces even after comments)

It actually does this when copying-and-pasting in new code. Do you also want this to happen when saving code? It might be a bit awkward to have this happen while editing a file.

> is-...-set? need to also be available with special names for <breed>, not only turtle/link/patch/agent (btw a bit inconsistent to write agentset, but turtle-set, patch-set etc. although understandable since agentset term is ancestor of all)2
> turtle-set/patch-set/link-set need to also be available with special names for <breed>. If you implement inheritance (see relevant suggestion below) it would work with descendents too
> ...
> I'd prefer to see somekind of inheritance when defining breeds (e.g. breed [mammals mammal] breed [cats cat] of mammals) where common properties would be defined/shared at the ancestor breed). You'd internally implement possibly with a class equivalence function where w
hen one asked for all mammals, the equivalent(mammals,dogs) and equivalent(mammals,cats) check would return true (I guess now you use = when you construct agentset given a breed-related query). BTW Java's "Class" class has more proper names for inheritance checking method
s (see its API - has separate checking for descendence and equivalence etc.). BTW could implement multiple-inheritance using say "breed [mules mule] of [horses donkeys]" (supposing mule was indeed a superset of both races)

Inheritance would be a major feature that would require substantial thought.
At the moment, I see it as a hard-to-implement feature that would have some limited benefits for a relatively small group of users.
If you can give us more feedback from users who would like to see this, or examples of things that are now totally impossible (ant not merely more difficult) that become possible with inheritance I think it's something that the CCL would discuss at greater length.

`is-breed-set?` is an interesting idea. There are two ways I can imagine this working:

1. `is-breed-set?` checks that all agents in the set are a member of the given breed (e.g. `all? agentset [ is-a-sheep? ]`).
2. `is-breed-set?` checks that the agentset was created using the `<breed>-set` primitive (e.g. `is-sheep-set? (sheep-set ...)`).

The 2nd idea is fairly close to how this is done presently (although of course, there are only 3 types of agentset). The 1st idea could probably be implemented quite quickly, although it would add another primitive which could be defined just as easily by the user.

> there should be an alternative tick form as (tick number) equivalent to tick-advance number

At the moment we have `tick` which always ticks by one, updates plots and the view.
We also have `tick-advance` which ticks by a fractional amount, updates the view *sometimes* and never updates plots.
Would this alternative form of tick update plots and/or views?

> using { output-show word "Vetoed to " ([master] of myself) } works ok but { output-show word "Vetoed to " [master] of myself } doesn't (shows two lines, first saying "Vetoed to " and second just writing e.g. (connector 5) : (connector 5)

I tried this out using `ask one-of patches [ show word "abc " [self] of self ]` in 6.0-Beta1 and I get the same result whether or not I included parens.
I suspect this may have been a precedence or parsing bug which has since been corrected.

> type and output-type should optionally accept any number of params (write ...) and (output-write ...)

All of the output commands accept only a single argument.
I don't see a compelling reason to make any of them variadic, with the possible exception of `write` / `output-write`.
The `write` primitives are special because they render each argument in such a way that it can be read back into netlogo as an object using `read-from-string`.

> type (applies to output-type too) doc should say "Its output will not include quotes around strings unlike write. "
> doc says at write: "Its output will also includes quotes". Should write "include" instead
> doc says at write "output value, which can be a number, string, list, boolean, or nobody" but not saying anything about the kind of value (apart from speaking about quotes in strings) at print/show/type (btw, I'd also expect some comments/examples on how lists are shown
 [with brackets? and also about sublists])

I agree the documentation for these primitives is unclear and somewhat inconsistent.
As far as I can tell, they could be laid out much more clearly in a table form:

| prim | accepts type | adds newline | readable | prints calling agent |
|------|--------------|--------------|----------|----------------------|
| write | boolean, number, string, list containing only types that can be written | no | yes | no |
| type  | any netlogo type | no | no | no |
| show | any netlogo type | yes | yes | yes |
| print | any netlogo type | yes | no | no |

The current documentation also states that `nobody` can be used as an argument to `write`.
While this was true in 5.3.1, it's no longer true in 6.0.

> doc at <breed>-own says "If you specify a breed instead of "turtles", only turtles of that breed have the listed variables. (More than one breed may list the same variable.)" but the compiler doesn't allow it (did you mean to say that if "turtles-own" is used instead al
l breeds get that variable?
> ...
> not consistent to allow COLOR for both links and turtles (whereas patches have pcolor) but not allow to have same-named custom variables at different breeds (may have parser issues if changed [pitty], but if can't would expect lcolor for links for consistency)

I'm not entirely certain based on the description what this is discussing, but I believe it's multiple breeds having breeds-own variables with the same name.
The following worked for me in 6.0-Beta1 (it's possible this was broken in earlier versions):

```NetLogo
breed [as a]
breed [bs b]

as-own [y z]
bs-own [z x]
```

The reason we use `pcolor` as opposed to `color` for patches is because turtles can also access the variables of their patch.
If we allowed turtles to automatically access the variables of their links, we probably *would* call it `lcolor`.
Of course, a turtle may only have one patch, but may have multiple links. So I think this change is unlikely, especially given that links have now used `color` for so long.


> allow more instances of the same view (like viewports / numbered and named) and in 3D too (e.g. in a car racing you have mirrors or you may have a zoomed out map of a big world etc.). If could have transparent patches then one could have overlapping views too (like a sm
all semi-tranparent map of a world at one of its corners)

This is partially covered by inspector windows, but the new-in-NetLogo-6 `ls` extension also offers some options here for alternate models with their own views.

> allow cloning GUI items (clone would be instantiated at x+ofs,y+ofs)

This seems like a fine idea. We've talked before about making widgets in NetLogo copy-pastable and I've made an issue for that [here](https://github.com/NetLogo/NetLogo/issues/1206).
I think if a widget is copy-pastable, that pretty much covers the "clone" use case.

> allow multiple (numbered/named) output areas (e.g. one might want to show instructions at other place than resuls or have separate result areas etc.)

While I can see the appeal of this, I would probably prefer making the "Note" widget have settable text content.
Perhaps a note can have an optional name and we could introduce an `update-note <note-name> <new-text>` primitive?
Would that address the issue here?

This issue strikes me as one with a high cost that I would want to get more information about the importance of before beginning work.

> alt down at observer/commandinput history dropdown and at any dropdownlist on the GUI should drop the list (as on Windows)

Some of the desire for this in the command center may be met in part by the auto-suggest action coming in NetLogo 6.0
I created an issue [here](https://github.com/NetLogo/NetLogo/issues/1207), please comment if there are other places you would like to see the shortcut active which aren't listed.

> mouse-zcor (3D mouse / see DirectInput on Windows)

As far as I can tell, DirectInput's z-axis is based on the mouse wheel. 
While it's straightforward to represent xcor and ycor, the mouse wheel seems problematic because it isn't tied to an absolute value (there is no floor or ceiling on mouse rotation) and it's also hard to tell when mouse-wheel events should be counted (for instance, should
all mouse wheel events be counted, only while it's over the view, only while the view has focus).
I think this idea has some potential, but it needs a lot more elaboration.

> optional to params checked at runtime given as 2nd optional list at TO0
> also empty list to mean any num of params, accessed via a paramslist (all params) or maybe an optionalparamslist with just the optional ones (I prefer to always have a paramslist function for any proc, even if it doesn't have optional params)

I agree that NetLogo procedures aren't very flexible at the moment.
I think there's a tension here between NetLogo's goals of high-threshold and low-ceiling.
For each new potential case you introduce to procedure syntax, that's one more thing that new users have to learn (and learn to interpret in other people's code).
At the moment, having only one (two if you count `to-report`) ways to declare a procedure makes NetLogo syntax very simple

> right-clicking output area should show "Clear" action to clear its current text

Great idea! I've opened an issue [here](https://github.com/NetLogo/NetLogo/issues/1208).

> pressing F1 at 1st char of row with just spaces or at empty row (or right click / Quick Help) says "could not be found in NetLogo Dictionary...etc.". Should open dictionary directly in that case (that is when search token is of empty length). Same happens if one selects
 Look up in dictionary from Help menu when in Interface tab
> pressing F1 at other than the leftmost pos of a row with just spaces doesn't offer to show help dialog! (same does when right-clicking at other than the leftmost pos on the row of spaces and selecting QuickHelp - doesn't open dictionary)

Would it be useful to add a separate shortcut key (Cmd-F1/Ctrl-F1 maybe?) which always opens the dictionary?
The danger in opening the dictionary on an empty token is that the cursor isn't where the user thinks it is, so the dictionary opens to the top and they see information irrelevant to the thing they **think** they asked for help with, so they conclude that quick-help is br
oken.
By only opening the dictionary when a token is clear, the user has a chance to correct their initial selection if they choose a space between two words or if they're off by a line.

> there's no do-while command that would execute a block once then evaluate condition for loop (for completness it would be also nice to have until and do-until)

I think these belong in an extension.

> at any? says see also all instead of all?

I don't see this in the manual, my guess is that it was a defect that was fixed some time ago.

> all? takes a reporter - I think any? should optionally take a reporter too

I could definitely see this happening, but it doesn't seem compatible with the earlier suggestion to make `any?` and `empty?` synonyms.

> edit / select all doesn't select all widgets (is only for text editor?)
> right-clicking empty area of GUI should have select all option and if any selection also have an Unselect All

"Select All" is only for the text editor. We could either disable it within the interface tab or implement it. Seems like it would fall under the purview of making widgets copy-pastable (issue [here](https://github.com/NetLogo/NetLogo/issues/1206))

> should say maybe deselect intead of unselect?

Yes, this should be fixed, and will be in NetLogo 6

> add edit/format menu action to format source (shown only when in source pane) and at context popup of source editor

Totally agree. Issue opened [here](https://github.com/NetLogo/NetLogo/issues/1209)

> rename Quick Help to Definition - holding down ctrl over a command at code editor or at the event script dialog (or at command center) should highlight it and clicking on it should scroll to its definition in the procedures tab (or to its documentation if its a primitiv
e). Need to make the event script window floating [with z order to keep it always on top] instead of modal - try JInternalFrame maybe or if there's related option at JDialog

6.0 will have a less-advanced version of this feature in the form of "Jump to Definition." Please let us know how you like it and how it can be improved!

> at script editor should have questionmark button at top-right before the [x] to show help on how to use the dialog - same could be at the main netlogo windown

Are you proposing adding a questionmark button to each tab at top right? I think that's a pretty decent idea.

> double-clicking yellow error bar should scroll the error line (the highlighted one) into view (JScrollPane or the edit box has such function I think). Same should do at script dialog for completness

The erroring line is currently scrolled-to automatically when opening a widget editor or the code tab with an error.
I wouldn't be opposed to adding a double click, but I don't think it's asking too much of our users to hit the "Check" button in the code tab a second time or close and re-open the widget dialog to recenter the error.

> colorchart image not shown at .../docs/programming.html#colors

I see a colorchart there. Perhaps this was an earlier bug that's already been fixed.

> when navigating with arrow keys to pos after [ or ] one should be able to press CTRL+DOWN and CTRL+UP respectively to go to the respective matching ] or [ (same should do at ctrl+click on a [ or ]). Similar should do for parentheses

Great idea. Created an issue [here](https://github.com/NetLogo/NetLogo/issues/1210).

> let/set should accept list of variable names as 1st parameter to define/init and set value of multiple variables respectively (to same expression for all - avoiding thus the recalculation of the expression or having to use local variable to 1st keep the expression, plus gaining in conciseness

I see this as a win for brevity but think it adds a lot of complexity to `let`/`set` as you have to determine whether the first argument is a literal list or the name of a variable.
As the primary maintainer of the compiler, I also think this would add a substantial amount of backend complexity.

> apart from link-length, link-heading and link-set should also have <breed>-length, <breed>-heading and <breed>-set for undirected/directed link breeds

`link-length` and `link-heading` can be used on link breeds already. Re: `<breed>-set`, I left thoughts above about being able to create a breed-specific agentset.

> can-move? distance
> Reports true if the calling turtle can move distance in the direction it is facing without violating the topology; reports false otherwise.
> It is equivalent to:
> patch-ahead distance != nobody
> Is this equivalent indeed? I'd expect can-move? to check all the path till that distance for missing patches (no corridor to the target patch), whereas patch-ahead isn't expected to do such thing

This is equivalent, at least in the existing NetLogo topologies.
The NetLogo topologies don't permit "holes", at least not as far as I'm aware. They either wrap or don't wrap in a given dimension. If they wrap, the turtle can always move around the wrap. If they don't wrap, the turtle can't move past the edge of the topology.

> extensions should be able to define help files for the QuickHelp feature (e.g. pressing F1 on profiler:start finds nothing now) and have a sample on how to build correctly the help file (with correct style and bookmarks)

Similar features are frequently requested. The most recent request can be found [here](https://github.com/NetLogo/NetLogo/issues/623).

> link-set {and patch-set respectively} say:
> "List inputs to LINK-SET {PATCH-SET} must only contain link {patch}, link {patch} agentset, or list elements. The list ... contained ... which is NOT a turtle {...} or turtle {...} agentset". It should not have "NOT" in that error message when you've indeed mistakenly say given a turtle in that set

When running `link-set [2]` I see the following:
```
List inputs to LINK-SET must only contain link, link agentset, or list elements.  The list [2] contained 2 which is NOT a link or link agentset.
error while observer running LINK-SET
  called by Command Center
```

This seems to indicate that this problem has been fixed

> Why can't one place a report inside an ask?

Preventing `report` inside `ask` ensures that `ask` is always run once for each agent in the agentset unless *that agent* runs `stop` (which will `stop` the ask only for them).
Allowing `report` within the `ask` would cause the `ask` to terminate with only some of the agents having run the specified code.
Using `report` on the result of an `of` and `with` is more idiomatic NetLogo (and conceptually clearer, I think).


> could have "TO breed:action" and TO [breed1 breed2 ...]:action" (could even not have a : and use a space since actions can't have same name as breeds). Compiler could then check that you don't run a command that is allowed only for certain breeds to other ones (not sure if consistent with hatching from one breed another one though)
> could also have x:[cmds] and [x y]:[cmds] as alternative to ASK and x:[reporter] as alternative to [reporter] of x (see previous one - could have "." instead of ":" for similarity to other languages)

I think it would be possible to produce a really cool object-oriented-esque version of NetLogo using such an idea, but I think a language which did so would substantially from NetLogo's core design goals and philosophy.

**Comment by mrerrormessage** [comment] 2017-02-27 18:09
Haven't heard any further feedback on the questions here. I'm going to go ahead and close this issue.

**Closed by mrerrormessage** 2017-02-27 18:09 UTC
