### ISSUE TITLE
macOS 10.15 (Catalina) complains about NetLogo app

### ISSUE THREAD

**Issue by SethTisue** [NetLogo/NetLogo#1788] opened 2019-10-09 01:54 UTC
<img width="587" alt="Screen Shot 2019-10-08 at 6 53 46 PM" src="https://user-images.githubusercontent.com/161079/66445853-1338d480-e9fd-11e9-9431-fac868a58b76.png">

perhaps related: #1302

**Comment by SethTisue** [comment] 2019-10-09 01:56
andi f I click "Open", the app bounces once, then closes.

**Comment by LaCuneta** [comment] 2019-10-09 17:55
Hey Seth, thanks for the report.  I see [Apple requires "notarization" in addition to signing on Catalina](https://developer.apple.com/documentation/security/notarizing_your_app_before_distribution), so we'll have to look into that.

On the one Catalina Mac I have access to I'm not able to reproduce the problem, probably because of other changes/tweaks we've done on the system.  I'll see if we can get another Mac in the lab updated for testing.

If you're able to check a few things for us:

- Check your Security & Privacy preferences and see if the app appears after failing to open in the general tab per [the instructions here](https://support.apple.com/en-us/HT202491) under the **How to open an app that hasn’t been notarized or is from an unidentified developer** section.  If NetLogo shows up there, clicking **Open Anyway** should let it start.
- If that doesn't work, can you try the `sudo xattr -dr com.apple.quarantine /Applications/NetLogo\ 6.1.1/NetLogo\ 6.1.1.app` workaround from #1302 to see if that fixes the issue?
- If that doesn't work, one more thing to try is to do a Control-Click to launch NetLogo.  I saw this reported as a solution in a few similar support threads, and it's worth a try even though it seems unlikely to work.

If one of those helps, we'll at least have something to advise Catalina users they can do until we see if we can get NetLogo desktop notarized through Apple.

**Comment by SethTisue** [comment] 2019-10-09 18:21
when I go the "Open Anyway" route via System Preferences, I get this dialog:

<img width="587" alt="Screen Shot 2019-10-09 at 11 19 33 AM" src="https://user-images.githubusercontent.com/161079/66508841-c0a3fa80-ea86-11e9-9b14-c0143110e819.png">

but clicking "Open" does not successfully launch the app.

after the `sudo ...` thing, it does successfully launch.

**Comment by LaCuneta** [comment] 2019-10-09 18:26
Nice, thank you for testing for us, and good to know our workaround still gets NetLogo running.  I'll keep looking into proper notarization.

**Comment by woswos** [comment] 2019-10-12 20:04
> Hey Seth, thanks for the report. I see [Apple requires "notarization" in addition to signing on Catalina](https://developer.apple.com/documentation/security/notarizing_your_app_before_distribution), so we'll have to look into that.
> 
> On the one Catalina Mac I have access to I'm not able to reproduce the problem, probably because of other changes/tweaks we've done on the system. I'll see if we can get another Mac in the lab updated for testing.
> 
> If you're able to check a few things for us:
> 
> * Check your Security & Privacy preferences and see if the app appears after failing to open in the general tab per [the instructions here](https://support.apple.com/en-us/HT202491) under the **How to open an app that hasn’t been notarized or is from an unidentified developer** section.  If NetLogo shows up there, clicking **Open Anyway** should let it start.
> * If that doesn't work, can you try the `sudo xattr -dr com.apple.quarantine /Applications/NetLogo\ 6.1.1/NetLogo\ 6.1.1.app` workaround from #1302 to see if that fixes the issue?
> * If that doesn't work, one more thing to try is to do a Control-Click to launch NetLogo.  I saw this reported as a solution in a few similar support threads, and it's worth a try even though it seems unlikely to work.
> 
> If one of those helps, we'll at least have something to advise Catalina users they can do until we see if we can get NetLogo desktop notarized through Apple.

I had a similar issue. For me, app was not opening at all.  Using `sudo xattr -dr com.apple.quarantine /Applications/NetLogo\ 6.1.1/NetLogo\ 6.1.1.app` solved the problem for me. Thank you so much.

**Comment by LaCuneta** [comment] 2019-11-04 17:19
I believe we now have a properly notarized macOS dmg package of 6.1.1 available on the NetLogo CCL site.   Testing on a couple Catalina computers I had access to succeeded when they'd previously failed on the older package.  If anyone else who had the issue wants to download a fresh copy of 6.1.1 and re-test, that would be welcome.

I'm going to leave the issue open for a little while longer to see if we have any other reports coming in.

**Comment by LaCuneta** [comment] 2019-11-18 17:23
Closing as we've not had any more reports, and at least one external user reported the new package got things working for them.

**Closed by LaCuneta** 2019-11-18 17:23 UTC
