### ISSUE TITLE
NetlLogo clearing interface variables

### ISSUE THREAD

**Issue by cstaelin** [NetLogo/NetLogo#1505] opened 2017-10-04 14:02 UTC
I have not investigated this fully, but when I open a model with NetLogo 3D 6.0.2 that has an error in the code, all the values of the interface variables seem to be cleared.  If, before doing anything else, I open the .nlogo3D file in Notepad++, I see that the section with the interface variable information still contains the proper values for the variables even as the Interface tab in the open model shows them to have all been zeroed out.  If I then save the model, it saves with the zeroed out values.  The code error typically is in an .nls file, I have a lot of them (.nls files, that is), but I haven't tested to see if an error in the .nlogo3D file results in the same behavior.  Has this arisen before?  (There are times when I just can't finish fixing errors before having to put a project aside, thus the fact that it opens with errors.)

**Comment by SethTisue** [comment] 2017-10-04 15:15
probably a duplicate of #1502

**Closed** 2017-10-04 15:15 UTC
