### ISSUE TITLE
`in-radius` and `in-cone` are O(n^2) for agentsets that aren't a breedset

### ISSUE THREAD

**Issue by qiemem** [NetLogo/NetLogo#1190] opened 2016-10-31 21:42 UTC
[Relevant code](https://github.com/NetLogo/NetLogo/blob/7eb938f273ae6b30344d9bf6caa73063463be521/netlogo-gui/src/main/agent/InRadiusOrCone.java#L99-L110):

```
            for (Turtle turtle : patch.turtlesHere()) {
              if (world.protractor().distance(turtle.xcor(), turtle.ycor(), startX, startY, wrap) <= radius &&
                  (sourceSet == world.turtles() ||
                      // any turtle set with a non-null print name is either
                      // the set of all turtles, or a breed agentset - ST 2/19/04
                      (sourceSet.printName() != null &&
                          sourceSet == turtle.getBreed()) ||
                      (sourceSet.printName() == null &&
                          sourceSet.contains(turtle)))) {
                result.add(turtle);
              }
            }
```

When `sourceSet` is not a breedset, `sourceSet.contains` is *always* called for turtles that are in bounds. Non-breed agentsets are `ArrayAgentSet` and `ArrayAgentSet.contains` is O(n).

The solution would be to create a hashset version of the `sourceSet` and do contains checks on that.

A few things to consider:

- This may useful enough that we should have `ArrayAgentSet.contains` cache a `HashSet` version of itself on the first contains check. This works because `ArrayAgentSet` is immutable. Agents can die, but they don't actually need to be removed from the `HashSet`.
- It could even be constructed lazily (only adding as many agents as you need until you find the target agent, and keep track the index you stopped at) so the upfront cost would be lower.
- Constructing `HashSet`s has a high constant factor, high enough that it could be a significant hit when only looking up a few agents. Some helpful things that make it less bad: we know the `HashSet` size upfront, so no reallocations have to take place. Furthermore, hashing agents is fast, since it just uses their ids, and equals checks on them are just identity checks.
- Give the constant factor hit, it might be better to just construct the hashset in `InRadius`.

**Comment by nicolaspayette** [comment] 2016-11-01 17:03
Duplicate of #402? (Though `in-cone` is not mentioned over there.) Also related:  #375.

**Comment by qiemem** [comment] 2016-11-02 15:32
#402: Quite related, but not the same. That issue is about patchsets, this issue is about turtlesets. The "make `contains` fast" fix is the same in both cases, if it happens in `ArrayAgentSet` itself. However, the constraints around patches and turtles are quite different (namely in that patch coordinates don't change) that makes them different enough to not combine the issues in my opinion.

#375: Related, but again quite different. Honestly, I'm not sure why we haven't done #375 yet... Maybe I'll try to do it after I finish the link stuff. Anyway, it would solve the special case of this problem of `n > r^2`.

**Comment by qiemem** [comment] 2016-11-02 15:35
Oh I suppose we could also do the strategy suggested in #375 for *all* `ArrayAgentSet`s. That would kind of suck for small `r`, but we wouldn't have to add any extra data structures, and it would be strictly better than the state of things.

**Closed** 2017-02-23 17:43 UTC
