### ISSUE TITLE
Error Occurred While Running Experiment in Behavior Space

### ISSUE THREAD

**Issue by ljoplin** [NetLogo/NetLogo#889] opened 2015-11-29 01:14 UTC
This is a copy of the error message.  I had a value in the wrong spot for one of the variables.  Took it out and it started running fine....then before finishing my computer shut down :-1:   Maybe next time 

NetLogo is unable to supply you with more details about this error.  Please report the problem
at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the
contents of this window into your report.

org.nlogo.api.ValueConstraint$Violation: Value must be a number.
 at org.nlogo.agent.SliderConstraint.assertConstraint(SliderConstraint.scala:70)
 at org.nlogo.agent.Observer.assertVariableConstraint(Observer.java:112)
 at org.nlogo.agent.Observer.setObserverVariable(Observer.java:119)
 at org.nlogo.agent.World.setObserverVariableByName(World.java:1349)
 at org.nlogo.lab.Worker$Runner$$anonfun$setVariables$1$4.apply(Worker.scala:128)
 at org.nlogo.lab.Worker$Runner$$anonfun$setVariables$1$4.apply(Worker.scala:122)
 at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:59)
 at scala.collection.immutable.List.foreach(List.scala:76)
 at org.nlogo.lab.Worker$Runner.setVariables$1(Worker.scala:122)
 at org.nlogo.lab.Worker$Runner.callHelper(Worker.scala:167)
 at org.nlogo.lab.Worker$Runner.call(Worker.scala:91)
 at org.nlogo.lab.Worker$Runner.call(Worker.scala:74)
 at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
 at java.util.concurrent.FutureTask.run(FutureTask.java:138)
 at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
 at java.lang.Thread.run(Thread.java:662)

NetLogo 5.2.1
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
Java HotSpot(TM) Server VM 1.6.0_45 (Sun Microsystems Inc.; 1.6.0_45-b06)
operating system: Windows Vista 6.0 (x86 processor)
Scala version 2.9.2
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: W4.Linda.Joplin

06:43:06.656 JobRemovedEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) JobThread
06:43:06.656 JobRemovedEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) JobThread
06:43:06.656 JobRemovedEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) JobThread
06:43:06.656 JobRemovedEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) JobThread
06:43:06.647 JobRemovedEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) JobThread
06:43:06.647 JobRemovedEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) JobThread
06:43:06.646 JobRemovedEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) JobThread
06:43:06.646 JobRemovedEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) JobThread
06:43:06.646 JobRemovedEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) JobThread
06:43:06.639 JobRemovedEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) JobThread

**Comment by SethTisue** [comment] 2015-11-30 16:19
duplicate of #818 (related: #551)

**Closed by SethTisue** 2015-11-30 16:19 UTC
Labels: duplicate
