### ISSUE TITLE
NetLogo is unable to supply you with more details about this error.

### ISSUE THREAD

**Issue by tastyfriedcats** [NetLogo/NetLogo#1304] opened 2017-02-01 07:27 UTC
Some background.  I have been working with a modefied version of the Simple Economy model found in the Models Library.  I have added a sub routine to the go procedure which models debt with interest.  This eventually causes the total amount of wealth to increase.  After some time, i receive  the following error message (below) along with  a prompt to report the problem.  Any suggestions?

java.lang.NullPointerException
 at org.nlogo.nvm.StackTraceBuilt.computeRuntimeErrorMessage(EngineException.scala:37)
 at org.nlogo.nvm.StackTraceBuilt.computeRuntimeErrorMessage$(EngineException.scala:36)
 at org.nlogo.nvm.RuntimePrimitiveException.computeRuntimeErrorMessage(EngineException.scala:51)
 at org.nlogo.nvm.EngineException.runtimeErrorMessage$lzycompute(EngineException.scala:29)
 at org.nlogo.nvm.EngineException.runtimeErrorMessage(EngineException.scala:28)
 at org.nlogo.nvm.Context.buildRuntimeErrorMessage(Context.java:368)
 at org.nlogo.nvm.Context.buildRuntimeErrorMessage(Context.java:363)
 at org.nlogo.window.ErrorInfo.$anonfun$errorMessage$3(RuntimeErrorDialog.scala:35)
 at scala.Option.map(Option.scala:146)
 at org.nlogo.window.ErrorInfo.errorMessage(RuntimeErrorDialog.scala:34)
 at org.nlogo.window.LogoExceptionDialog.buildTexts(RuntimeErrorDialog.scala:238)
 at org.nlogo.window.LogoExceptionDialog.doShow(RuntimeErrorDialog.scala:224)
 at org.nlogo.window.RuntimeErrorDialog$.$anonfun$show$1(RuntimeErrorDialog.scala:102)
 at org.nlogo.window.RuntimeErrorDialog$.$anonfun$show$1$adapted(RuntimeErrorDialog.scala:102)
 at scala.Option.foreach(Option.scala:257)
 at org.nlogo.window.RuntimeErrorDialog$.show(RuntimeErrorDialog.scala:102)
 at org.nlogo.window.GUIWorkspace$12.run(GUIWorkspace.java:1059)
 at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
 at java.awt.EventQueue.access$500(EventQueue.java:97)
 at java.awt.EventQueue$3.run(EventQueue.java:709)
 at java.awt.EventQueue$3.run(EventQueue.java:703)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
 at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
 at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

NetLogo 6.0
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_112 (Oracle Corporation; 1.8.0_112-b15)
operating system: Windows 10 10.0 (amd64 processor)
Scala version 2.12.1
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: simple_economy

05:18:29.093 SwitchedTabsEvent (org.nlogo.app.Tabs) AWT-EventQueue-0
05:18:29.092 RuntimeErrorEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
05:18:29.091 JobRemovedEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) JobThread
05:18:29.083 AddJobEvent (org.nlogo.window.ButtonWidget) AWT-EventQueue-0
05:18:29.017 InterfaceGlobalEvent (org.nlogo.widget.SwitchWidget) AWT-EventQueue-0
05:18:29.017 InterfaceGlobalEvent (org.nlogo.window.ChooserWidget) AWT-EventQueue-0
05:18:29.017 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
05:18:29.017 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
05:18:28.971 InputBoxLoseFocusEvent (org.nlogo.window.ButtonWidget) AWT-EventQueue-0
05:18:28.814 InterfaceGlobalEvent (org.nlogo.widget.SwitchWidget) AWT-EventQueue-0

**Comment by mrerrormessage** [comment] 2017-02-01 14:44
Thanks for reporting! This looks like the same issue as https://github.com/NetLogo/NetLogo/pull/1277, which we have a fix for that will be included with the next release of NetLogo. It's caused when numbers get too large and was a regression introduced in 6.0.

**Closed by mrerrormessage** 2017-02-01 14:44 UTC
