### ISSUE TITLE
Will next version support Macbook M1?

### ISSUE THREAD

**Issue by lofyer** [NetLogo/NetLogo#2049] opened 2022-09-24 08:21 UTC
I've compared Netlogo 6.2.2 with latest(6.3.0-beta) on my Macbook 14' M1 pro to find out that the latter performance  is about twice of the 6.2.2.
JDK: zulu-17.jdk(apple m1 version)
Test model: ants.

**Comment by SethTisue** [comment] 2022-09-24 15:35
duplicate of #2016

**Closed by SethTisue** 2022-09-24 15:35 UTC
