### ISSUE TITLE
5.2.1 regression: weirdly large font size in output area

### ISSUE THREAD

**Issue by SethTisue** [NetLogo/NetLogo#896] opened 2015-12-05 04:01 UTC
Matrix Example with font size of output area set to 12. left is 5.2, right is 5.2.1. 5.2.2-RC2 is similar to 5.2.1

<img width="854" alt="screen shot 2015-12-04 at 11 01 07 pm" src="https://cloud.githubusercontent.com/assets/161079/11605915/024f7b4e-9adb-11e5-8e3d-e82e55583a3d.png">

**Comment by nicolaspayette** [comment] 2015-12-05 04:05
I hope it's not a regression caused by https://github.com/NetLogo/NetLogo/pull/805, but it could be...

**Comment by mrerrormessage** [comment] 2015-12-07 19:07
I'm pretty sure that the problem is related to [this call to `fontSize(Int)`](https://github.com/NetLogo/NetLogo/blob/5.x/src/main/org/nlogo/window/OutputWidget.scala#L73). When creating an output widget in a new model, the font is sized normally, but if saved and reopened, the font is noticeably larger. I'm not clear enough on how widgets are loaded to know what changes need to be made, but perhaps you all have some ideas?

**Comment by SethTisue** [comment] 2015-12-07 21:58
the horror, the horror

**Comment by nicolaspayette** [comment] 2015-12-08 19:36
Two parts to this:

- The bigger font in Matrix Example was most probably a consequence of #802 (the bug that was fixed by #805). It was introduced (by me) in https://github.com/NetLogo/models/commit/5e586ed6360ac2d624b120f7ac9eafbe0095bb78 and is now fixed by https://github.com/NetLogo/models/commit/0c4aaaf40db9eb1937fe52675d70bbcc9877b7ba.

- There was, nonetheless, a regression introduced by #805: the line that @mrerrormessage rightly suspected to be guilty should have been using the proper `fontSize_=` setter instead of directly setting `outputArea.fontSize`. That explains why the "Edit..." dialog for the output widget was showing the font as being 12 points even if it was actually 20. This should be fixed by https://github.com/NetLogo/NetLogo/pull/899.

**Comment by mrerrormessage** [comment] 2015-12-09 16:18
Closed by #899

**Closed** 2015-12-09 16:17 UTC
