### ISSUE TITLE
Add CTRL+click to navigate to procedure definition

### ISSUE THREAD

**Issue by birbilis** [NetLogo/NetLogo#792] opened 2015-06-11 12:38 UTC
Would be nice to allow right-click on procedure name to navigate to a procedure, like in NetBeans or Visual Studio (with Productivity Tools extension in older versions of it).

The functionality to jump to procedures is already there after all (at the dropdown on the top)

So the main functionality that would be needed is to be able to underline temporarily (although this isn't very much needed, gives user a useful hint the feature is available) the current symbol under the mouse cursor if user holds down CTRL and the symbol is a procedure name

Could do the same for variables maybe (and also add respective dropdown) if some record is kept on where those are defined - easy to implement if variable names are globally unique (don't remember what is the case with NetLogo), else you have to know the context (subtree of code) where mouse cursor is over, so you need the in-memory-tree (if you have such) to know start-end line of each tree node

**Comment by SethTisue** [comment] 2015-06-12 13:11
duplicate of #544

**Closed by SethTisue** 2015-06-12 13:11 UTC
Labels: duplicate
