### ISSUE TITLE
NetLogo Should Stop Execution on Empty Input

### ISSUE THREAD

**Issue by TheBizzle** [NetLogo/NetLogo#386] opened 2013-07-08 18:39 UTC
Steve Railsback writes:

> One of our students just discovered an unfortunate situation that NetLogo doesn't handle very well: if you create an "Input" widget on the interface, for a global variable that is a number, and fail to enter a value.
>
> If you try to run the model, then a dialog pops up "Invalid input for a number". You can hit "OK" to kill this dialog, but it pops back up as soon as the model tries to keep running and use the variable again. You cannot use "Tools/Halt" to kill the run because the "Invalid input..." box pops up first.
>
> This was especially a problem when the student started a BehaviorSpace run with an empty Input... we had to manually kill NetLogo.
>
> It might be more helpful to just halt execution in the case of an empty or invalid input.
>
> (I'm using v. 5.0.3)

**Comment by SethTisue** [comment] 2015-09-01 21:37
duplicate of #682

**Closed by SethTisue** 2015-09-01 21:37 UTC
Labels: enhancement
