### ISSUE TITLE
NetLogo 3D 6.1.1 not running on Ubuntu 20.04

### ISSUE THREAD

**Issue by nikitamankovskii** [NetLogo/NetLogo#1872] opened 2020-11-24 09:19 UTC
Hello,
I have the issue with running NetLogo 3D 6.1.1
with usual run, it just start loading and give this:
```
$ ./NetLogo3D
NetLogo3D Error invoking method.
NetLogo3D Failed to launch JVM
```
In case of running with throw `.jar` file:
```
java -Dorg.nlogo.is3d=true -jar ./netlogo-6.1.1.jar
```
output is this:
```
NetLogo is unable to supply you with more details about this error.  Please report the problem 
 at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the 
contents of this window into your report. 


java.lang.reflect.InvocationTargetException
 at java.awt.EventQueue.invokeAndWait(EventQueue.java:1349)
 at java.awt.EventQueue.invokeAndWait(EventQueue.java:1324)
 at org.nlogo.awt.EventQueue$.invokeAndWait(EventQueue.scala:19)
 at org.nlogo.app.App$.mainWithAppHandler(App.scala:161)
 at org.nlogo.app.App$.main(App.scala:67)
 at org.nlogo.app.App.main(App.scala)
Caused by: com.jogamp.opengl.GLException: Profile GL2 is not available on null, but: [GLProfile[GL4ES3/GL4.hw], GLProfile[GL2ES2/GL4.hw], GLProfile[GL4/GL4.hw], GLProfile[GL4/GL4.hw], GLProfile[GL3/GL4.hw], GLProfile[GL2GL3/GL4.hw]]
 at com.jogamp.opengl.GLProfile.get(GLProfile.java:991)
 at com.jogamp.opengl.GLProfile.get(GLProfile.java:1004)
 at org.nlogo.gl.view.View.createCanvas(View.scala:47)
 at org.nlogo.gl.view.View.<init>(View.scala:39)
 at org.nlogo.gl.view.ObserverView.<init>(ObserverView.scala:8)
 at org.nlogo.gl.view.ObserverView.<init>(ObserverView.scala:11)
 at org.nlogo.gl.view.ViewManager.init(ViewManager.scala:62)
 at org.nlogo.gl.view.ViewManager.open(ViewManager.scala:42)
 at org.nlogo.window.GUIWorkspace.open3DView(GUIWorkspace.java:758)
 at org.nlogo.window.GUIWorkspace.handle(GUIWorkspace.java:745)
 at org.nlogo.window.Events$AfterLoadEvent.beHandledBy(Events.java:138)
 at org.nlogo.window.Event.doRaise(Event.java:198)
 at org.nlogo.window.Event.raise(Event.java:122)
 at org.nlogo.window.ReconfigureWorkspaceUI$Loader.$anonfun$loadHelper$5(ReconfigureWorkspaceUI.scala:41)
 at org.nlogo.window.ReconfigureWorkspaceUI$Loader.$anonfun$loadHelper$5$adapted(ReconfigureWorkspaceUI.scala:41)
 at scala.collection.immutable.List.foreach(List.scala:392)
 at org.nlogo.window.ReconfigureWorkspaceUI$Loader.loadHelper(ReconfigureWorkspaceUI.scala:41)
 at org.nlogo.window.ReconfigureWorkspaceUI$.apply(ReconfigureWorkspaceUI.scala:19)
 at org.nlogo.app.FileManager.org$nlogo$app$FileManager$$runLoad(FileManager.scala:303)
 at org.nlogo.app.FileManager.openFromModel(FileManager.scala:361)
 at org.nlogo.app.FileManager.newModel(FileManager.scala:323)
 at org.nlogo.app.App.loadDefaultModel(App.scala:570)
 at org.nlogo.app.App.org$nlogo$app$App$$finishStartup(App.scala:452)
 at org.nlogo.app.App$.$anonfun$mainWithAppHandler$1(App.scala:161)
 at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
 at java.awt.EventQueue.access$500(EventQueue.java:97)
 at java.awt.EventQueue$3.run(EventQueue.java:709)
 at java.awt.EventQueue$3.run(EventQueue.java:703)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
 at org.GNOME.Accessibility.AtkWrapper$6.dispatchEvent(AtkWrapper.java:705)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
 at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
 at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

NetLogo 3D 6.1.1
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-1
OpenJDK 64-Bit Server VM 1.8.0_275 (Private Build; 1.8.0_275-8u275-b01-0ubuntu1~20.04-b01)
operating system: Linux 5.4.0-54-generic (amd64 processor)
Scala version 2.12.8
JOGL: (3D View not initialized)

OpenGL Graphics: (3D View not initialized)
model: Untitled

01:06:14.302 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-1
01:06:14.004 AfterLoadEvent (org.nlogo.window.ReconfigureWorkspaceUI$Loader (java.lang.Object)) AWT-EventQueue-1
01:06:13.993 CompiledEvent (org.nlogo.window.CompilerManager) AWT-EventQueue-1
01:06:13.978 CompiledEvent (org.nlogo.window.CompilerManager) AWT-EventQueue-1
01:06:13.899 RemoveAllJobsEvent (org.nlogo.window.CompilerManager) AWT-EventQueue-1
01:06:13.844 LoadEndEvent (org.nlogo.window.ReconfigureWorkspaceUI$Loader (java.lang.Object)) AWT-EventQueue-1
01:06:13.835 ResizeViewEvent (org.nlogo.window.ViewWidget) AWT-EventQueue-1
01:06:13.831 ResizeViewEvent (org.nlogo.window.ViewWidget) AWT-EventQueue-1
01:06:13.828 ResizeViewEvent (org.nlogo.window.ViewWidget) AWT-EventQueue-1
01:06:13.827 PatchesCreatedEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-1
```

Im on Ubuntu 20.04
Java 1.8.0_275
NetLogo 3D 5.0.5 working fine

**Comment by LaCuneta** [comment] 2020-12-01 14:48
@nikitamankovskii Thank you for reporting this issue, and sorry you ran into it.  

This problem appears to be a duplicate of this older issue:  https://github.com/NetLogo/NetLogo/issues/1699

We just released NetLogo 6.1.2-beta2, and it includes an updated version of the JOGL 3D library we use to render NetLogo 3D.  Even though it's marked as a beta for testing, it should be stable and all functionality should work as you would expect.

Can you download this version and see if it works better than 6.1.1 did?  It's available on our download site, just change the version dropdown to *NetLogo 6.1.2-beta2* from the default of *NetLogo 6.1.1*.  https://ccl.northwestern.edu/netlogo/download.shtml

Since this is a duplicate I'm going to close this issue, but please update here or on the original issue if you get a chance to test the beta and it does or does not work for you.

**Closed by LaCuneta** 2020-12-01 14:48 UTC

**Comment by yasirroni** [comment] 2021-03-23 10:52
NetLogo 6.2.0 with Ubuntu 20.04 seems not works either. I'm trying the basic `./NetLogo` (not the 3D).

```
    $ cd netlogo-6.2.0-*
    $ ./NetLogo
```
Is this issue not fixed yet?

**Comment by LaCuneta** [comment] 2021-03-23 13:05
@yasirroni This issue only has to do with NetLogo 3D, and it was fixed with the NetLogo 6.2.0 release.  We tested running both NetLogo 6.2.0 3D and non-3D with Ubuntu 20.04 and it works on our systems.  If you're having trouble running NetLogo 6.2.0 on Ubuntu 20.04, that would be a new issue.  You can email bugs@ccl.northwestern.edu with any error messages you are getting, along with any other info on your system you are able provide (32 or 64 bit, memory, processor, etc), and we'll see what we can do.  Thanks.

**Comment by brandesNW** [comment] 2021-03-23 14:22
Hi,
As Jeremy indicated, NetLogo 6.2.0 with Ubuntu 20.04 works

Is it possible that you haven’t extracted NetLogo from the download archive?
Directions follow
The download  file is
NetLogo-6.2.0-64.tgz. or NetLogo-6.2.0-32.tgz

For example I downloaded the file from https://ccl.northwestern.edu/netlogo/6.2.0/
into my Downloads directory

So I have a file ~/Downloads/NetLogo-6.2.0-64.tgz

To  extract it  into  ~/ NetLogo 6.2.0
$ cd
$ tar -xf ~/Downloads/NetLogo-6.2.0-64.tgz

$  ls
app/                         'Mathematica Link'/   netlogo-headless.sh*
Behaviorsearch*   NetLogo*              'NetLogo User Manual.pdf'
HubNetClient*    NetLogo3D*            readme.md
libpackager.so    netlogo-gui.sh*      runtime/

where the * indicates an executable file, and the / indicates a directory
To run NetLogo
$ cd NetLogo\ 6.2.0/
$. ./NetLogo

Let us know if you need further assistance.
Aaron

--
Aaron Brandes, Software Developer
Center for Connected Learning and Computer-Based Modeling


From: Muhammad Yasirroni ***@***.***>
Reply-To: NetLogo/NetLogo ***@***.***>
Date: Tuesday, March 23, 2021 at 6:53 AM
To: NetLogo/NetLogo ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [NetLogo/NetLogo] NetLogo 3D 6.1.1 not running on Ubuntu 20.04 (#1872)


NetLogo 6.2.0 with Ubuntu 20.04 seems not works either. I'm trying the basic ./NetLogo (not the 3D).

    $ cd netlogo-6.2.0-*

    $ ./NetLogo

Is this issue not fixed yet?

**Comment by yasirroni** [comment] 2021-03-23 14:52
I'm testing `NetLogo 6.0.2-64 bit` and its worked. Previously, it's my fault to try to run `NetLogo 6.2.0-32 bit` in 64 bit system. 

I'll check `NetLogo 6.2.0-64 bit` throws error or not and if error occurred, I'll post the details.

Thank you for the fast response.

**Comment by yasirroni** [comment] 2021-03-23 15:02
Solved, the problem (culprit) is running 32 bit version on Ubuntu 64 bit. Miss clicked the version on download (my fault).

Thank you.

Just weird why it throws error:

```shell
NetLogo Error invoking method.
NetLogo Failed to launch JVM
```

when using 32 bit version on 64 bit systems.

**Comment by LaCuneta** [comment] 2021-03-23 15:08
@yasirroni Gotcha, thanks for following up.  That error is strange and uninformative, but it's good to have it documented here in your comment in case anyone else runs into it.
