### ISSUE TITLE
Genes- protein Synthesis

### ISSUE THREAD

**Issue by thordarsonc** [NetLogo/NetLogo#1904] opened 2021-02-16 13:43 UTC
The simulation won't run "show protein synthesis" on any computer from the web browser or downloaded version.

**Comment by brandesNW** [comment] 2021-02-16 15:36
Can you please share a link or other method of accessing the model you refer to?
The only models that are "vetted" by the folks maintaining NetLogo are those in the NetLogo Models Library.
There is a similarly named "DNA Protein Synthesis" model in the NetLogo Library, although it does not have command called  "show protein synthesis."

To run that model you need to press "setup" and then "go/stop." You can then proceed to press the numbered steps in order, starting with 1. transcribe and continuing until 7. release.

Two other library models that might be of interest to you are "GenEvo 1 Genetic Switch" and "Synthetic Biology - Genetic Switch"

We would like to resolve your problem, so please verify if you are now able to use "DNA Protein Synthesis" or help us reproduce your issue. Thanks for your interest in NetLogo. 
Aaron

**Comment by thordarsonc** [comment] 2021-02-16 16:50
[http://genes.inquiry-hub.net/](url)

**Comment by brandesNW** [comment] 2021-02-16 17:47
Hi, 
Thanks for you quick reply. I have been able to get this to work both online, and in a downloaded version.
Please note that the result of protein production is _not_ shown visually. You need to look in the command center to see the results. 

To exactly reproduce my output just add a line setting the random seed. 
```
to setup
  clear-all
  random-seed 1953
```

For example: with nucleotides-affected =1 and mutation-type = substitution

> Proteins Produced
> from original DNA  = 1
> ::::::::::::::::::
> Orig.Gene #1 > Protein:
> -Met-Glu-Leu-Ser-Trp-His-Val-Val-Phe-Ile-Ala-Leu-Leu-Ser-Phe-Ser-Cys-Trp-Gly
>
> ==================
> Proteins Produced
> from copy of DNA = 1
> ::::::::::::::::::
> Copy.Gene #1 > Protein:
> -Met-Glu-Leu-Ser-Trp-His-Val-Val-Phe-Ile-Ala-Leu-Leu-Ser-Phe-Ser-Cys-Trp-Gly

In some cases no proteins are produced. `setup` and `go` again
setting nucleotides-affected =1 and mutation-type = deletion


> Proteins Produced
> from original DNA  = 0
> ::::::::::::::::::
> ==================
> Proteins Produced
> from copy of DNA = 0
> ::::::::::::::::::

Note: the way the code is implemented means that protein production for the original strand will only be attempted if the mutated copy can produce protein. 

Please let us know if this works for you so I can close the issue if appropriate.

**Comment by brandesNW** [comment] 2021-02-18 20:41
This issue is being closed because the model, which is not part of the NetLogo Models Library, appears to be working correctly.
Comments can still be added.

**Closed by brandesNW** 2021-02-18 20:41 UTC
