### ISSUE TITLE
Extreme runtime speed difference between updates on ticks and continuously, irrespective of frame rate

### ISSUE THREAD

**Issue by cbradyatinquire** [NetLogo/NetLogo#745] opened 2015-03-27 04:15 UTC
With the following simple code, there is an extreme difference between updates on ticks and continuous updates. (Updating on ticks is radically slower.)  Changing the "frame rate" in the view settings does not seem to alter the speed of running with updates on ticks at all.

to setup
 ca
 crt 100
 reset-ticks
end

to go
  ask turtles [ wander ]
  tick
end

to wander
  rt -20 + random 41
  fd .1
end

**Comment by SethTisue** [comment] 2015-03-27 12:23
duplicate of #741

**Closed by SethTisue** 2015-03-27 12:23 UTC

**Comment by SethTisue** [comment] 2015-03-27 12:24
because "note that there is a separate possibility of having an additional setting that says whether at the default setting, frames may be skipped or not (in order to hit the frame rate target)"
