### ISSUE TITLE
Energy Budget Model Error

### ISSUE THREAD

**Issue by SophieMay93** [NetLogo/NetLogo#1415] opened 2017-06-04 19:12 UTC
Internal error in energy budget model

java.lang.NullPointerException
 at org.nlogo.nvm.StackTraceBuilt.computeRuntimeErrorMessage(EngineException.scala:37)
 at org.nlogo.nvm.StackTraceBuilt.computeRuntimeErrorMessage$(EngineException.scala:36)
 at org.nlogo.nvm.RuntimePrimitiveException.computeRuntimeErrorMessage(EngineException.scala:51)
 at org.nlogo.nvm.EngineException.runtimeErrorMessage$lzycompute(EngineException.scala:29)
 at org.nlogo.nvm.EngineException.runtimeErrorMessage(EngineException.scala:28)
 at org.nlogo.nvm.Context.buildRuntimeErrorMessage(Context.java:368)
 at org.nlogo.nvm.Context.buildRuntimeErrorMessage(Context.java:363)
 at org.nlogo.window.ErrorInfo.$anonfun$errorMessage$3(RuntimeErrorDialog.scala:35)
 at scala.Option.map(Option.scala:146)
 at org.nlogo.window.ErrorInfo.errorMessage(RuntimeErrorDialog.scala:34)
 at org.nlogo.window.LogoExceptionDialog.buildTexts(RuntimeErrorDialog.scala:238)
 at org.nlogo.window.LogoExceptionDialog.doShow(RuntimeErrorDialog.scala:224)
 at org.nlogo.window.RuntimeErrorDialog$.$anonfun$show$1(RuntimeErrorDialog.scala:102)
 at org.nlogo.window.RuntimeErrorDialog$.$anonfun$show$1$adapted(RuntimeErrorDialog.scala:102)
 at scala.Option.foreach(Option.scala:257)
 at org.nlogo.window.RuntimeErrorDialog$.show(RuntimeErrorDialog.scala:102)
 at org.nlogo.window.GUIWorkspace$12.run(GUIWorkspace.java:1059)
 at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
 at java.awt.EventQueue.access$500(EventQueue.java:97)
 at java.awt.EventQueue$3.run(EventQueue.java:709)
 at java.awt.EventQueue$3.run(EventQueue.java:703)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
 at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
 at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

NetLogo 6.0
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_112 (Oracle Corporation; 1.8.0_112-b15)
operating system: Windows 10 10.0 (amd64 processor)
Scala version 2.12.1
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: Red Deer Energy Budget

08:09:11.854 JobRemovedEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) JobThread
08:09:11.854 SwitchedTabsEvent (org.nlogo.app.Tabs) AWT-EventQueue-0
08:09:11.822 RuntimeErrorEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
08:09:11.666 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
08:09:11.666 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
08:09:11.666 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
08:09:11.463 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
08:09:11.463 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
08:09:11.463 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
08:09:11.260 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0

**Comment by SethTisue** [comment] 2017-06-04 20:23
does it also happen in NetLogo 6.0.1?

**Comment by SophieMay93** [comment] 2017-06-04 20:34
Just re-ran it in NetLogo 6.0.1 and got more information on the error as shown below. I will check in my code and see if I can fix it. Help would still be appreciated if you think of an easy fix! 

math operation produced a non-number
error while female 102 running ^
  called by procedure CALC_GROWTH
  called by procedure GO
  called by Button 'Go'

org.nlogo.nvm.RuntimePrimitiveException: math operation produced a non-number
 at org.nlogo.nvm.Instruction.invalidDouble(Instruction.scala:357)
 at org.nlogo.nvm.Instruction.validDouble(Instruction.scala:343)
 at org.nlogo.prim._asm_procedurecalc_growth_setprocedurevariable_1.perform(:9)
 at org.nlogo.nvm.Context.runExclusive(Context.java:135)
 at org.nlogo.nvm.ExclusiveJob.run(ExclusiveJob.scala:39)
 at org.nlogo.nvm.Context.runExclusiveJob(Context.java:181)
 at org.nlogo.prim._asm_procedurego_ask_9.perform(:1)
 at org.nlogo.nvm.Context.stepConcurrent(Context.java:107)
 at org.nlogo.nvm.ConcurrentJob.step(ConcurrentJob.scala:65)
 at org.nlogo.job.JobThread.runPrimaryJobs(JobThread.scala:133)
 at org.nlogo.job.JobThread.$anonfun$run$1(JobThread.scala:68)
 at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
 at scala.util.control.Exception$Catch.apply(Exception.scala:224)
 at org.nlogo.api.Exceptions$.handling(Exceptions.scala:41)
 at org.nlogo.job.JobThread.run(JobThread.scala:66)

NetLogo 6.0.1
main: org.nlogo.app.AppFrame
thread: JobThread
Java HotSpot(TM) 64-Bit Server VM 1.8.0_121 (Oracle Corporation; 1.8.0_121-b13)
operating system: Windows 10 10.0 (amd64 processor)
Scala version 2.12.1
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: Red Deer Energy Budget

09:33:24.716 SwitchedTabsEvent (org.nlogo.app.Tabs) AWT-EventQueue-0
09:33:24.708 RuntimeErrorEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
09:33:24.637 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
09:33:24.637 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
09:33:24.637 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
09:33:24.428 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
09:33:24.428 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
09:33:24.428 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
09:33:24.285 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
09:33:24.285 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0

**Comment by SethTisue** [comment] 2017-06-04 22:25
ah, duplicate of #1277 then

**Closed by SethTisue** 2017-06-04 22:25 UTC

**Comment by SethTisue** [comment] 2017-06-04 22:27
as for advice, it depends what computation you're doing in your `CALC_GROWTH` procedure and where the numbers you're passing to the `^` primitive are coming from. example input that might produce this error: `-1 ^ 0.5`

**Comment by SophieMay93** [comment] 2017-06-05 06:05
That's what I thought, the calculation itself seems find but there must be a point at which one of the parameters drops below 0. I'll focus on that! Thank you
