### ISSUE TITLE
Unknown error 

### ISSUE THREAD

**Issue by cogijl** [NetLogo/NetLogo#1031] opened 2016-04-28 15:00 UTC
Tried to start up a model that has worked previously after running a behaviorspace experiment. Now when the model is opened it doesn't crash but it cannot be run or checked and it displays the error below:

NetLogo is unable to supply you with more details about this error.  Please report the problem
at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the
contents of this window into your report.

java.lang.reflect.InvocationTargetException
 at java.awt.EventQueue.invokeAndWait(EventQueue.java:1319)
 at java.awt.EventQueue.invokeAndWait(EventQueue.java:1294)
 at org.nlogo.awt.EventQueue$.invokeAndWait(EventQueue.scala:19)
 at org.nlogo.swing.ModalProgressTask$Boss.run(ModalProgressTask.scala:61)
Caused by: org.xml.sax.SAXParseException; systemId: jar:file:/C:/Program%20Files/NetLogo%205.3/app/NetLogo.jar!/system/; lineNumber: 56; columnNumber: 66; The content of element type "enumeratedValueSet" is incomplete, it must match "(value)+".
 at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
 at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:134)
 at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:396)
 at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
 at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:284)
 at com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.handleEndElement(XMLDTDValidator.java:1994)
 at com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.emptyElement(XMLDTDValidator.java:769)
 at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:1344)
 at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2787)
 at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
 at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
 at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
 at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
 at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
 at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:243)
 at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
 at org.nlogo.lab.ProtocolLoader$Loader.load(ProtocolLoader.scala:61)
 at org.nlogo.lab.ProtocolLoader.loadAll(ProtocolLoader.scala:31)
 at org.nlogo.lab.gui.LabManager.handle(LabManager.scala:47)
 at org.nlogo.window.Events$LoadSectionEvent.beHandledBy(Events.java:471)
 at org.nlogo.window.Event.doRaise(Event.java:198)
 at org.nlogo.window.Event.raise(Event.java:122)
 at org.nlogo.window.ModelLoader$Loader$$anonfun$loadHelper$1.apply(ModelLoader.scala:101)
 at org.nlogo.window.ModelLoader$Loader$$anonfun$loadHelper$1.apply(ModelLoader.scala:101)
 at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:59)
 at scala.collection.immutable.List.foreach(List.scala:76)
 at org.nlogo.window.ModelLoader$Loader.loadHelper(ModelLoader.scala:101)
 at org.nlogo.window.ModelLoader$.load(ModelLoader.scala:16)
 at org.nlogo.window.ModelLoader.load(ModelLoader.scala)
 at org.nlogo.app.FileMenu$1.run(FileMenu.java:859)
 at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
 at java.awt.EventQueue.access$500(EventQueue.java:97)
 at java.awt.EventQueue$3.run(EventQueue.java:709)
 at java.awt.EventQueue$3.run(EventQueue.java:703)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
 at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
 at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
 at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
 at java.awt.Dialog.show(Dialog.java:1084)
 at java.awt.Component.show(Component.java:1673)
 at java.awt.Component.setVisible(Component.java:1625)
 at java.awt.Window.setVisible(Window.java:1014)
 at java.awt.Dialog.setVisible(Dialog.java:1005)
 at org.nlogo.swing.ModalProgressTask$.apply(ModalProgressTask.scala:43)
 at org.nlogo.swing.ModalProgressTask.apply(ModalProgressTask.scala)
 at org.nlogo.app.FileMenu.openFromMap(FileMenu.java:869)
 at org.nlogo.app.FileMenu.openFromSource(FileMenu.java:841)
 at org.nlogo.app.FileMenu.openFromPath(FileMenu.java:795)
 at org.nlogo.app.App$$anonfun$open$1.apply$mcV$sp(App.scala:800)
 at org.nlogo.app.App$$anonfun$open$1.apply(App.scala:800)
 at org.nlogo.app.App$$anonfun$open$1.apply(App.scala:800)
 at org.nlogo.app.App.dispatchThreadOrBust(App.scala:1018)
 at org.nlogo.app.App.open(App.scala:800)
 at org.nlogo.app.App.loadDefaultModel(App.scala:501)
 at org.nlogo.app.App.org$nlogo$app$App$$finishStartup(App.scala:440)
 at org.nlogo.app.App$$anonfun$mainWithAppHandler$1.apply$mcV$sp(App.scala:141)
 at org.nlogo.swing.Implicits$$anon$17.run(Implicits.scala:12)
 at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
 at java.awt.EventQueue.access$500(EventQueue.java:97)
 at java.awt.EventQueue$3.run(EventQueue.java:709)
 at java.awt.EventQueue$3.run(EventQueue.java:703)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
 at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
 at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

NetLogo 5.3
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_65 (Oracle Corporation; 1.8.0_65-b17)
operating system: Windows 8.1 6.3 (amd64 processor)
Scala version 2.9.2
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: Agent_Zeno_2_4

10:57:58.915 LoadSectionEvent (org.nlogo.window.ModelLoader$Loader (java.lang.Object)) AWT-EventQueue-0
10:57:58.911 LoadSectionEvent (org.nlogo.window.ModelLoader$Loader (java.lang.Object)) AWT-EventQueue-0
10:57:58.911 LoadSectionEvent (org.nlogo.window.ModelLoader$Loader (java.lang.Object)) AWT-EventQueue-0
10:57:58.910 WidgetAddedEvent (org.nlogo.window.ButtonWidget) AWT-EventQueue-0
10:57:58.909 CompileMoreSourceEvent (org.nlogo.window.ButtonWidget) AWT-EventQueue-0
10:57:58.909 RemoveJobEvent (org.nlogo.window.ButtonWidget) AWT-EventQueue-0
10:57:58.907 WidgetAddedEvent (org.nlogo.widget.SwitchWidget) AWT-EventQueue-0
10:57:58.906 InterfaceGlobalEvent (org.nlogo.widget.SwitchWidget) AWT-EventQueue-0
10:57:58.903 WidgetAddedEvent (org.nlogo.window.PlotWidget) AWT-EventQueue-0
10:57:58.885 WidgetAddedEvent (org.nlogo.window.PlotWidget) AWT-EventQueue-0

**Comment by mrerrormessage** [comment] 2016-04-28 15:11
Thanks for opening an issue! Would you mind providing the model file to this issue? You can attach it to this issue (you may need to put it in a zip archive first) or email it to ccl-bugs _at_ ccl _dot_ northwestern _dot_ edu. If you email, please reference the github issue number.

**Comment by SethTisue** [comment] 2016-04-29 01:10
duplicate of #252 ?

**Comment by mrerrormessage** [comment] 2016-05-02 20:39
Yes, I'm closing this as a duplicate.

**Closed** 2016-05-17 21:34 UTC
Labels: bug
