### ISSUE TITLE
heading through a corner with pendown

### ISSUE THREAD

**Issue by pioucyril** [NetLogo/NetLogo#926] opened 2016-02-01 23:47 UTC
Hi all, 
I crossed a very strange bug when the world is wrapped around with 0,0 on lower left corner, a turtle heading is 225, its pen is down and arrive at a negative position (e.g. -0.23 -0.23) and it is asked to fd 1... the system then hang in endless computation.
You can reproduce that with the following code, given that your world setting is as described above:

ca
crt 1 [
setxy 1 1
set heading 225
pendown
]
ask turtle 0 [fd 10]

Operating system: Windows (several tested at least XP and 7pro)
Version Netlogo: 5 and above (several tested)

Actually, it does hang as well when the origin is on the top-right corner and the turtle has a 45 heading... see attached file
[test.zip](https://github.com/NetLogo/NetLogo/files/113187/test.zip)

Keep up the great work!
Cheers.

**Comment by SethTisue** [comment] 2016-02-01 23:54
thanks for the report! almost certainly a duplicate of https://github.com/NetLogo/NetLogo/issues/361

**Comment by mrerrormessage** [comment] 2016-02-05 22:11
This is fixed on 5.x. Fix should appear in the 5.3.1 release.

**Closed by mrerrormessage** 2016-02-05 22:11 UTC
Labels: duplicate
