### ISSUE TITLE
Not sure what is the issue

### ISSUE THREAD

**Issue by cristicorrea** [NetLogo/NetLogo#1567] opened 2018-02-16 23:17 UTC
NetLogo is unable to supply you with more details about this error.  Please report the problem 
 at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the 
contents of this window into your report. 

java.awt.IllegalComponentStateException: component must be showing on the screen to determine its location
 at java.awt.Component.getLocationOnScreen_NoTreeLock(Component.java:2062)
 at java.awt.Component.getLocationOnScreen(Component.java:2036)
 at javax.swing.text.JTextComponent$InputMethodRequestsHandler.getTextLocation(JTextComponent.java:4643)
 at sun.awt.im.InputMethodContext.getTextLocation(InputMethodContext.java:278)
 at sun.awt.windows.WInputMethod$1.run(WInputMethod.java:588)
 at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
 at java.awt.EventQueue.access$500(EventQueue.java:97)
 at java.awt.EventQueue$3.run(EventQueue.java:709)
 at java.awt.EventQueue$3.run(EventQueue.java:703)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
 at java.awt.EventQueue$4.run(EventQueue.java:731)
 at java.awt.EventQueue$4.run(EventQueue.java:729)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
 at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
 at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

NetLogo 6.0.2
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_141 (Oracle Corporation; 1.8.0_141-b15)
operating system: Windows 10 10.0 (amd64 processor)
Scala version 2.12.2
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: Model0215 Base Case Traditional Chain

04:14:16.912 InterfaceGlobalEvent (org.nlogo.window.InputBoxWidget) AWT-EventQueue-0
04:14:16.912 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
04:14:16.912 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
04:14:16.912 InterfaceGlobalEvent (org.nlogo.window.ChooserWidget) AWT-EventQueue-0
04:14:16.912 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
04:14:16.912 InterfaceGlobalEvent (org.nlogo.window.ChooserWidget) AWT-EventQueue-0
04:14:16.912 InterfaceGlobalEvent (org.nlogo.window.InputBoxWidget) AWT-EventQueue-0
04:14:16.912 InterfaceGlobalEvent (org.nlogo.window.InputBoxWidget) AWT-EventQueue-0
04:14:16.912 InterfaceGlobalEvent (org.nlogo.window.ChooserWidget) AWT-EventQueue-0
04:14:16.912 InterfaceGlobalEvent (org.nlogo.window.InputBoxWidget) AWT-EventQueue-0

**Comment by mrerrormessage** [comment] 2018-02-18 13:05
Thanks for reporting! See [this comment](https://github.com/NetLogo/NetLogo/issues/436#issuecomment-366273591) for more details. This bug is Windows-10 specific and caused by the particular version of Java we bundle with NetLogo. The next release of NetLogo should include a fix for this.

**Closed by mrerrormessage** 2018-02-18 13:05 UTC
