### ISSUE TITLE
Compiler should complain if procedure name or procedure input name matches extension primitive

### ISSUE THREAD

**Issue by SethTisue** [NetLogo/NetLogo#347] opened 2013-05-15 14:22 UTC
for example these should be compile errors, but aren't (though the code doesn't work, either):

```netlogo
extensions [array]
to array:set end
to foo [array:set] end
```

**Comment by Idloj** [comment] 2015-08-28 10:03
Isn't this a duplicate of #248?

**Comment by SethTisue** [comment] 2015-08-28 12:33
yes, good catch. closed it.

**Closed** 2016-05-25 18:13 UTC
Labels: bug, compiler
