### ISSUE TITLE
Hidden context change if first line in procedure is a turtle command

### ISSUE THREAD

**Issue by jbadham** [NetLogo/NetLogo#1680] opened 2018-10-19 09:28 UTC
The following code (correctly) notifies a syntax error that you can't use xcor in an observer context.

```
to testme1
  create-turtles 3
  if xcor > 1 [set color red]
  tick
end
```

However, if the use of turtle context commands is the first line of the procedure, then NetLogo changes contexts. The following code notifies a syntax error that you can't use tick in a turtle context.

```
to testme2
  if xcor > 1 [set color red]
  tick
end
```

I detected this hidden context change when answering a question on StackOverflow, see [here](https://stackoverflow.com/questions/52865255/netlogo-ticks-as-a-counter-for-a-race)

**Comment by LaCuneta** [comment] 2018-10-19 14:10
Jen, thanks for checking on this issue, and thank you for providing great answers on StackOverflow.  This is actually working as intended.  NetLogo tries to be smart about detecting which context (turtle, observer, patch, or link) a user-defined procedure can execute with.  If it sees a procedure only uses turtle commands and variables, then you can use that procedure only in a turtle context.  And, as you found, you cannot mix the contexts together.

See the [`draw-polygon` example in the NetLogo docs](https://ccl.northwestern.edu/netlogo/docs/programming.html#procedures) for more.  

I'm going to close this issue, but feel free to leave a comment if you have more questions about it.

**Closed by LaCuneta** 2018-10-19 14:10 UTC

**Comment by jbadham** [comment] 2018-10-19 14:49
Fair enough and I agree that NetLogo should be clever enough to detect what is intended to be a turtle or patch or link or observer procedure. The errors are even informative if you're working at the 'top' layer. But I do see beginners getting into trouble with context switching as soon as there's any nesting involved. I will think further about what exactly would be helpful and put in a feature request for a human readable indicator for the context for each procedure, or for changes to error messages.
