### ISSUE TITLE
Add primitive for closing inspection windows 

### ISSUE THREAD

**Issue by TheBizzle** [NetLogo/NetLogo#716] opened 2015-02-24 20:33 UTC
Various CCLers (including Uri) have voiced support for a primitive that can close inspection windows (given that we can programmatically open them with `inspect`).  Here is my proposal for such a primitive:

> `stop-inspecting <agent>`: Closes any inspection window that is open for `<agent>`.  If no inspection window is open for `<agent>`, nothing happens.

I believe that Uri would like this primitive included in 5.2 (though I might be wrong).

**Comment by nicolaspayette** [comment] 2015-02-26 01:56
Duplicate of #354, by the way.

**Closed** 2015-02-26 02:26 UTC
Labels: duplicate
