### ISSUE TITLE
Link Agent Monitor Runtime Error when end1 is a number

### ISSUE THREAD

**Issue by brandesNW** [NetLogo/NetLogo#2228] opened 2024-03-15 19:04 UTC
To reproduce:

1) Open a new Link Monitor from the Tools Menu
2) For the end1 text box enter the number 0 and hit return or tab
3) An exception results

> java.lang.ClassCastException: class org.nlogo.core.Nobody$ cannot be cast to class org.nlogo.agent.Turtle (org.nlogo.core.Nobody$ and org.nlogo.agent.Turtle are in unnamed module of loader 'app')
>  at org.nlogo.agent.AgentManagement.$anonfun$getOrCreateDummyLink$1(AgentManagement.scala:100)
>  at scala.Option.getOrElse(Option.scala:189)
>  at org.nlogo.agent.AgentManagement.getOrCreateDummyLink(AgentManagement.scala:100)
>  at org.nlogo.agent.AgentManagement.getOrCreateDummyLink$(AgentManagement.scala:92)
>  at org.nlogo.agent.World.getOrCreateDummyLink(World.scala:108)
>  at org.nlogo.app.tools.AgentVarEditor.doAgentSwitch(AgentMonitorEditor.scala:358)
>  at org.nlogo.app.tools.AgentVarEditor.action(AgentMonitorEditor.scala:326)
>  at org.nlogo.app.tools.AgentVarEditor.keyPressed(AgentMonitorEditor.scala:236)
>  at java.desktop/java.awt.Component.processKeyEvent(Unknown Source)
>  at java.desktop/javax.swing.JComponent.processKeyEvent(Unknown Source)

**Comment by LaCuneta** [comment] 2024-03-15 19:39
Duplicate of #1999

**Closed by LaCuneta** 2024-03-15 19:39 UTC

**Comment by brandesNW** [comment] 2024-03-15 20:00
Hi Jeremy,
Your original issue seems to imply that who numbers may have worked at some point. Do you know if they ever did?
You indicated that the problem goes back to at least 6.0.4.
I tried running NetLogo 6.0 on my MacOS system, but running sudo xattr -dr com.apple.quarantine /Applications/NetLogo\ 6.0/NetLogo\ 6.0.app did not help.
What input gets them to work now? If no values for end1 and end2 work there seems to be no point in letting the user open a Link Monitor from the Tools Menu. They should only be opened using the inspect command on a link.
Thanks,
Aaron
--
Aaron Brandes, Software Developer
Center for Connected Learning and Computer-Based Modeling


From: Jeremy B ***@***.***>
Date: Friday, March 15, 2024 at 3:40 PM
To: NetLogo/NetLogo ***@***.***>
Cc: Aaron Andre Brandes ***@***.***>, Author ***@***.***>
Subject: Re: [NetLogo/NetLogo] Link Agent Monitor Runtime Error when end1 is a number (Issue #2228)

Closed #2228<https://urldefense.com/v3/__https:/github.com/NetLogo/NetLogo/issues/2228__;!!Dq0X2DkFhyF93HkjWTBQKhk!W5HEU4or8YcsuubkJ2ONg-eyPUs_jQH9JPvNrkZoyd1HAHBEytgC1j-nEjABGBlsoyBn9iOtLSROHAjXr5VNhoUGg-CGKTiNQg$> as not planned.
