### ISSUE TITLE
right click in user-file dialog box makes program unresponsive, losing changes

### ISSUE THREAD

**Issue by dougedmunds** [NetLogo/NetLogo#1097] opened 2016-07-13 20:53 UTC
Applies to Windows, not sure of other OS's.

When user-file opens a dialog box, if you  right click on a file in the directory
NetLogo becomes unresponsive.   Any changes to the file are lost when shutting
down the program.

To run, in observer area, type:

 `show user-file`

then right-click any file in the dialog box

**Comment by qiemem** [comment] 2016-07-13 21:02
Wow, that's pretty bad.

I would expect this to be platform specific, but just in case, I tested on OS X in both 5.3.1 and 6.0M8, and could not reproduce it.

**Comment by dougedmunds** [comment] 2016-07-13 21:06
Same issue if using File>Open in main menu (on Windows 10), then right clicking a file.

**Comment by Akarshit** [comment] 2016-07-14 11:54
Also not occurring on Linux.

**Comment by mrerrormessage** [comment] 2016-07-14 15:38
I tested this pretty thoroughly and found the following:

* This doesn't happen on Windows 7
* I can't get this to happen on Windows 10 by right-clicking and then clicking away or by choosing most options in the right-click menu (new file, copy, etc.). I tested this on a clean installation of Windows 10 with NetLogo 5.2.1 and NetLogo 5.3.1 (64-bit and 32-bit)
* I do see a hard freeze when choosing the "Delete" option from the right-click menu. I *sometimes* see a similar freeze when selecting a file and deleting it without right-clicking.

If you're seeing it *every* time you right click, whether or not you select any items, the cause of that seems likely to be something else tied to the way your machine is configured.

I plan to do a bit more investigating to see if I can produce a minimal version of the freeze on deletion to submit as a bug to Oracle, to be fixed (maybe) in a later version of Java. Even if I'm able to get a minimal reproducible case and open a bug report today, I would expect it to be months (at minimum) before this is resolved in NetLogo.

**Comment by dougedmunds** [comment] 2016-07-14 16:38
UPDATE:  The problem seems local to NetLogo 5.3.1 x64 {running on Win10x64 system).  I uninstalled it and replaced it with the NetLogo 5.3.1 x32 version.  I do not get this problem with the 32 bit version.  Right clicking is normal and fast.

**Comment by mrerrormessage** [comment] 2016-07-19 16:45
This has been accepted by Oracle as [JDK Bug 8161467](https://bugs.openjdk.java.net/browse/JDK-8161467). This issue will be revisited when and if a fix comes for that issue.

**Comment by mrerrormessage** [comment] 2017-02-27 18:13
Oracle have fixed this bug and backported the fix to JDK 8u121 (current version) in [this bug](https://bugs.openjdk.java.net/browse/JDK-8173350). This should be revalidated in the next build, but *should* be resolved in the next release!

**Comment by mrerrormessage** [comment] 2017-03-01 17:22
Testing shows that this was not resolved in Java 8u121. Guess we'll try again when 8u151/8u152 comes out in July (or when we upgrade to Java 9).

**Comment by mrerrormessage** [comment] 2018-02-27 17:39
Confirmed this is fixed in Java 8u162, which is what the next version of NetLogo will be based on. Closing.

**Closed by mrerrormessage** 2018-02-27 17:39 UTC
Labels: windows
