### ISSUE TITLE
LevelSpace bugs in Beta 1 6.0

### ISSUE THREAD

**Issue by ToonTalk** [NetLogo/NetLogo#1213] opened 2016-11-10 11:52 UTC
The library model "Model Visualizer and Plotter example" illustrates the problem.

After setup

observer> show [model-id] of turtles
observer: [7 7 7 0 7 7 7 7 3 7 7 7 7 7 7 7 3 7 3 7 7 7 1 7 3 1]

They should all be different, right? To me the turtle setup code looks fine.

And the turtles are displayed at more than the 4 locations despite there only being 4 different model ids. Maybe this is just a consequence of the turtles sharing the same model which gets a tick for each turtle owning it.

And after running for a long time many models have no population but no turtles go to 0,0 - though this may be a consequence of the incorrect initialisation above.

And the graph does not show any sheep when there clearly are some - the max is define as "min [count sheep] ls:of ls:models" instead of max ...

**Comment by ToonTalk** [comment] 2016-11-10 11:55
A fix is

    (ls:create-models 1 "../../../Sample Models/Biology/Wolf Sheep Predation.nlogo" [[?] -> set model-id ? ])

;    set model-id last ls:models  ; and assign model-id to the turtle

But I fail to see what was wrong with the original code.

**Comment by qiemem** [comment] 2016-11-10 15:09
Thanks for the report! The cause of this is NetLogo/LevelSpace#91. The fix will be included in the next beta.

**Closed by qiemem** 2016-11-10 15:09 UTC

**Comment by ToonTalk** [comment] 2016-11-10 15:19
Good.

Sorry that I combined two issues in one report but the LevelSpace sample model has this important typo in the graph code:

And the graph does not show any sheep when there clearly are some - the max is define as "min [count sheep] ls:of ls:models" instead of max ...

**Comment by qiemem** [comment] 2016-11-10 15:24
Ah, yes, sorry I missed that. That's also been fixed and should be in the next beta.
