### ISSUE TITLE
Add alignment and snapping lines to the interface tab to allow aligning widgets with each other

### ISSUE THREAD

**Issue by Idloj** [NetLogo/NetLogo#793] opened 2015-06-11 20:34 UTC
It's much more convenient if you want to place the widgets nicely.

**Comment by nicolaspayette** [comment] 2015-06-11 20:41
Agreed. Widget placement in general could be improved. (e.g., https://github.com/NetLogo/NetLogo/pull/774). Contextual menu options like "align with each other" or "distribute evenly" would also be nice.

**Comment by SethTisue** [comment] 2015-06-12 01:58
OmniGraffle is an example of an application with exemplary support for this.

**Comment by Idloj** [comment] 2015-06-12 05:41
Netbeans GUI editor too

**Comment by nicolaspayette** [comment] 2016-08-12 17:20
Also related: #343.

**Comment by SethTisue** [comment] 2016-08-12 17:38
this is actually just a straight-up duplicate of #343, isn't it?

**Comment by nicolaspayette** [comment] 2016-08-12 17:53
I thought @Idloj was suggesting what some programs call "alignment guides", which would be a slightly different proposal. Even then, the two issues could be consolidated.

**Closed** 2016-08-12 17:58 UTC
Labels: duplicate

**Comment by Idloj** [comment] 2016-08-13 20:50
> I thought @Idloj was suggesting what some programs call "alignment guides", which would be a slightly different proposal
That's right
