### ISSUE TITLE
BehaviorSpace crashes when clicking "Run" twice

### ISSUE THREAD

**Issue by nicolaspayette** [NetLogo/NetLogo#630] opened 2014-06-26 19:41 UTC
I've tested this in both 5.0.5 and 5.1RC2.

To reproduce:
- Open, for example, the "Fire" model from the library;
- Open BehaviorSpace, define a new experiment (e.g. vary `density` from 1 to 100) and click "OK";
- Select your experiment and click "Run";
- Fill in the "Run Options" dialog and click "OK" (options chosen do not matter);
- Choose where to save your output in the file dialog and click "Save";
- Now you're back to the BehaviorSpace dialog, and if your model is big enough or your computer slow enough, nothing happens for a few seconds and _it's awfully temping to click "Run" again_. And if you do, you get the exception below. (If your computer is too fast and you don't have time to click, try increasing to world size to, e.g., 200*200.)

Once the "Running experiment" window appears, the danger is averted because it's a modal window and you can't click "Run" anymore. Fixing the problem might be just a matter of having another, intermediate, modal window (e.g., "Preparing experiment...") appear in the meanwhile.

It's no big deal, in any case, but the "clicking Run" affordance is strong enough for me that I still get bitten by the bug even if _know_ that I should not click it.

Here is the exception:

```
Global variable does not exist:
density

org.nlogo.lab.Worker$Runner$FailedException: Global variable does not exist:
density
 at org.nlogo.lab.Worker$Runner$$anonfun$setVariables$1$4.apply(Worker.scala:126)
 at org.nlogo.lab.Worker$Runner$$anonfun$setVariables$1$4.apply(Worker.scala:122)
 at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:59)
 at scala.collection.immutable.List.foreach(List.scala:76)
 at org.nlogo.lab.Worker$Runner.setVariables$1(Worker.scala:122)
 at org.nlogo.lab.Worker$Runner.callHelper(Worker.scala:166)
 at org.nlogo.lab.Worker$Runner.call(Worker.scala:91)
 at org.nlogo.lab.Worker$Runner.call(Worker.scala:74)
 at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
 at java.util.concurrent.FutureTask.run(FutureTask.java:138)
 at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
 at java.lang.Thread.run(Thread.java:662)

NetLogo 5.0.5
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
Java HotSpot(TM) 64-Bit Server VM 1.6.0_45 (Sun Microsystems Inc.; 1.6.0_45-b06)
operating system: Linux 3.13.0-30-generic (amd64 processor)
Scala version 2.9.2
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: Fire

03:05:18.368 AddJobEvent (org.nlogo.window.MonitorWidget) AWT-EventQueue-0
03:05:18.368 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
03:05:18.368 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
03:05:18.368 JobRemovedEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) JobThread
03:05:18.367 RemoveJobEvent (org.nlogo.window.MonitorWidget) AWT-EventQueue-0
03:05:18.367 RuntimeErrorEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
03:05:18.212 WidgetAddedEvent (org.nlogo.window.PlotWidget) AWT-EventQueue-0
03:05:18.167 AddSliderConstraintEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
03:05:18.167 CompiledEvent (org.nlogo.window.CompilerManager) AWT-EventQueue-0
03:05:18.163 AddJobEvent (org.nlogo.window.MonitorWidget) AWT-EventQueue-0
```

**Comment by mrerrormessage** [comment] 2016-01-09 01:06
The button should be locked down when clicked until the job finishes or errors. The relevant section of code is [in ManagerDialog](https://github.com/NetLogo/NetLogo/blob/5.x/src/main/org/nlogo/lab/gui/ManagerDialog.scala). If necessary, a `SwingWorker` could be used to manage starting/stopping, as described in [this StackOverflow thread](http://stackoverflow.com/questions/17807846/disable-button-on-click-befor-actionperformed-is-competed-java).

**Comment by Idloj** [comment] 2016-01-10 13:32
or, as @nicolaspayette suggested,
> Fixing the problem might be just a matter of having another, intermediate, modal window (e.g., "Preparing experiment...") appear in the meanwhile.

**Comment by mister-walter** [comment] 2017-03-21 16:32
Unable to reproduce on an macOS Sierra machine or a (very slow) Windows 10 machine. I tested on 5.0.5, 5.1, and 6.0.

**Comment by mrerrormessage** [comment] 2017-03-22 16:07
I couldn't replicate this either on macOS Sierra (after multiple tries). I'm closing for now. This can be re-opened if we receive future reports.

**Closed by mrerrormessage** 2017-03-22 16:07 UTC
Labels: behaviorspace, bug, quickfix
