### ISSUE TITLE
IllegalComponentStateException when right-clicking while dragging a widget

### ISSUE THREAD

**Issue by nicolaspayette** [NetLogo/NetLogo#436] opened 2013-09-19 19:23 UTC
To reproduce:
- select any widget in a NetLogo model
- start dragging it across the screen
- right-click while still dragging

Only tested on Linux with 5.0.4 and 5.0.5RC1.

Here is the stack trace:

```
NetLogo is unable to supply you with more details about this error.  Please report the problem
at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the
contents of this window into your report.

java.awt.IllegalComponentStateException: component must be showing on the screen to determine its location
 at java.awt.Component.getLocationOnScreen_NoTreeLock(Component.java:1964)
 at java.awt.Component.getLocationOnScreen(Component.java:1938)
 at javax.swing.JPopupMenu.show(JPopupMenu.java:887)
 at org.nlogo.swing.WrappingPopupMenu.show(WrappingPopupMenu.java:21)
 at org.nlogo.app.WidgetWrapper.doPopup(WidgetWrapper.java:864)
 at org.nlogo.app.WidgetWrapper.mousePressed(WidgetWrapper.java:478)
 at java.awt.Component.processMouseEvent(Component.java:6285)
 at javax.swing.JComponent.processMouseEvent(JComponent.java:3267)
 at java.awt.Component.processEvent(Component.java:6053)
 at java.awt.Container.processEvent(Container.java:2041)
 at java.awt.Component.dispatchEventImpl(Component.java:4651)
 at java.awt.Container.dispatchEventImpl(Container.java:2099)
 at java.awt.Component.dispatchEvent(Component.java:4481)
 at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4577)
 at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4235)
 at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4168)
 at java.awt.Container.dispatchEventImpl(Container.java:2085)
 at java.awt.Window.dispatchEventImpl(Window.java:2478)
 at java.awt.Component.dispatchEvent(Component.java:4481)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:643)
 at java.awt.EventQueue.access$000(EventQueue.java:84)
 at java.awt.EventQueue$1.run(EventQueue.java:602)
 at java.awt.EventQueue$1.run(EventQueue.java:600)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
 at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:98)
 at java.awt.EventQueue$2.run(EventQueue.java:616)
 at java.awt.EventQueue$2.run(EventQueue.java:614)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:613)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:269)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:184)
 at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:174)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:169)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:161)
 at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

NetLogo 5.0.5-RC1
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
Java HotSpot(TM) 64-Bit Server VM 1.6.0_26 (Sun Microsystems Inc.; 1.6.0_26-b03)
operating system: Linux 3.8.0-30-generic (amd64 processor)
Scala version 2.9.2
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: simsci

03:15:33.643 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
03:15:33.643 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
03:15:33.643 InterfaceGlobalEvent (org.nlogo.widget.SwitchWidget) AWT-EventQueue-0
03:15:33.643 InterfaceGlobalEvent (org.nlogo.widget.SwitchWidget) AWT-EventQueue-0
03:15:33.643 InterfaceGlobalEvent (org.nlogo.widget.SwitchWidget) AWT-EventQueue-0
03:15:33.643 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
03:15:33.643 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
03:15:33.643 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
03:15:33.643 InterfaceGlobalEvent (org.nlogo.widget.SwitchWidget) AWT-EventQueue-0
03:15:33.643 InterfaceGlobalEvent (org.nlogo.widget.SwitchWidget) AWT-EventQueue-0
```

**Comment by fetr0509** [comment] 2015-03-06 20:43
More specifically on windows having an interface item selected and then right clicking on it followed by left clicking on it without releasing the right mouse button (no dragging required) will throw a similar Exception.

\\\\\\
Windows 7 professional
Netlogo 5.1.0
\\\\\

NetLogo is unable to supply you with more details about this error.  Please report the problem
at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the
contents of this window into your report.

java.awt.IllegalComponentStateException: component must be showing on the screen to determine its location
 at java.awt.Component.getLocationOnScreen_NoTreeLock(Component.java:1971)
 at java.awt.Component.getLocationOnScreen(Component.java:1945)
 at javax.swing.JPopupMenu.show(JPopupMenu.java:887)
 at org.nlogo.swing.WrappingPopupMenu.show(WrappingPopupMenu.java:21)
 at org.nlogo.app.WidgetWrapper.doPopup(WidgetWrapper.java:864)
 at org.nlogo.app.WidgetWrapper.mouseReleased(WidgetWrapper.java:581)
 at java.awt.Component.processMouseEvent(Component.java:6297)
 at javax.swing.JComponent.processMouseEvent(JComponent.java:3275)
 at java.awt.Component.processEvent(Component.java:6062)
 at java.awt.Container.processEvent(Container.java:2039)
 at java.awt.Component.dispatchEventImpl(Component.java:4660)
 at java.awt.Container.dispatchEventImpl(Container.java:2097)
 at java.awt.Component.dispatchEvent(Component.java:4488)
 at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4575)
 at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4236)
 at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4166)
 at java.awt.Container.dispatchEventImpl(Container.java:2083)
 at java.awt.Window.dispatchEventImpl(Window.java:2489)
 at java.awt.Component.dispatchEvent(Component.java:4488)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:674)
 at java.awt.EventQueue.access$400(EventQueue.java:81)
 at java.awt.EventQueue$2.run(EventQueue.java:633)
 at java.awt.EventQueue$2.run(EventQueue.java:631)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
 at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:98)
 at java.awt.EventQueue$3.run(EventQueue.java:647)
 at java.awt.EventQueue$3.run(EventQueue.java:645)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:644)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:269)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:184)
 at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:174)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:169)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:161)
 at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

NetLogo 5.1.0
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
Java HotSpot(TM) Server VM 1.6.0_45 (Sun Microsystems Inc.; 1.6.0_45-b06)
operating system: Windows 7 6.1 (x86 processor)
Scala version 2.9.2
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: Complex World States

12:41:11.089 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
12:41:11.088 InterfaceGlobalEvent (org.nlogo.window.InputBoxWidget) AWT-EventQueue-0
12:41:11.088 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
12:41:11.088 InterfaceGlobalEvent (org.nlogo.window.ChooserWidget) AWT-EventQueue-0
12:41:11.088 InterfaceGlobalEvent (org.nlogo.window.ChooserWidget) AWT-EventQueue-0
12:41:11.088 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
12:41:10.890 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
12:41:10.890 InterfaceGlobalEvent (org.nlogo.window.InputBoxWidget) AWT-EventQueue-0
12:41:10.890 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
12:41:10.890 InterfaceGlobalEvent (org.nlogo.window.ChooserWidget) AWT-EventQueue-0

**Comment by mrerrormessage** [comment] 2016-01-09 01:41
This should be straightforward to knock out, just modify [this conditional in WidgetWrapper](https://github.com/NetLogo/NetLogo/blob/5.x/src/main/org/nlogo/app/WidgetWrapper.java#L477) to only pop the edit menu when all of the following conditions are true:

1. The mouse event is a `popupTrigger` (it does this already)
2. The widget is not `selected`
3. The mouse event doesn't have `button1` pressed (use `org.nlogo.awt.Mouse`, as on Line 481)

Note that this is only possible to reproduce on Mac with a two-button mouse.

**Comment by mrerrormessage** [comment] 2016-04-29 20:01
Closed by #958

**Comment by mrerrormessage** [comment] 2017-11-13 21:22
This has been reported again on hexy. The change seems to have not gotten ported properly to 6.x.

**Comment by mrerrormessage** [comment] 2018-02-16 15:50
OK, so there was actually a very similar error that had was occurring in NetLogo 6.0.2, but that was actually caused by [this Java Bug](https://bugs.openjdk.java.net/browse/JDK-8179665). Having looked in-depth at the various reports I received (and checking that these changes are actually included on hexy), I feel confident in saying that this wasn't a regression, but a java bug with a superficially similar stacktrace which occurred around Java8u131 (6.0.2 was 8u141). This bug has been fixed in 8u152, 8u162, and since our builds from here on should use 8u162, I'm going to go ahead and re-close this.

**Closed by mrerrormessage** 2018-02-16 15:50 UTC
Labels: bug, good first issue
