### ISSUE TITLE
Extensions that are placed in the current folder are not found

### ISSUE THREAD

**Issue by luis-r-izquierdo** [NetLogo/NetLogo#1428] opened 2017-06-22 14:02 UTC
It seems that in NetLogo 6.0.1 (MacOS Sierra), if you place an extension only in the same folder as your NetLogo model, NetLogo does not find it. I've tried with the only extension that I've found updated for the new API:
https://github.com/cstaelin/Pathdir-Extension/releases
(and also in one that I am updating)

If you place the extension in the extensions folder located with the NetLogo installation, then everything works fine.

Thanks a lot!

**Comment by mrerrormessage** [comment] 2017-06-22 16:09
Thanks for reporting! We've been aware of this bug for a while and it was fixed in 2bff49a9c551083d6caa4324d5c74e56fdbf41d1 . Unfortunately, we don't have any plans to do a release soon, so it may not be available for a while. If you're comfortable running NetLogo from source, the issue is fixed in the `hexy` branch.

**Closed by mrerrormessage** 2017-06-22 16:09 UTC

**Comment by luis-r-izquierdo** [comment] 2017-06-22 18:00
That's great Robert, thanks a lot!
Luis
