### ISSUE TITLE
rescaling histograms

### ISSUE THREAD

**Issue by BruceEdmonds** [NetLogo/NetLogo#881] opened 2015-11-20 11:53 UTC
When using autoscale with histograms they reduce the scale when it is too large, but do not increase scale when it is too small. This means for simulations with very unequal histograms at the start (say one very tall bar) the subsequent scale is such that one can not see the bars after that.

One could calculate the tallest bar in NetLogo and change the scale explicitly but this is a computationally expensive process.

Can we either:
1. change the autoscale behaviour so it scales both up and down depending on the current plot
OR
2. provide a new primitive that returns the maximum height of any histogram call so one can rescale appropriately
OR
3. allow programmers access to the binned results from the histogram command so we can calculate the maximum height

Thanks

**Comment by SethTisue** [comment] 2015-11-20 13:28
duplicate of #744

**Comment by SethTisue** [comment] 2015-11-20 13:28
the "access to the binned results" part is https://github.com/NetLogo/NetLogo/issues/367

**Closed by SethTisue** 2015-11-20 13:28 UTC
