### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Jurrrrr** [NetLogo/NetLogo#2214] opened 2024-02-06 08:20 UTC
NetLogo is unable to supply you with more details about this error.  Please report the problem 
 at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the 
contents of this window into your report. 

java.lang.ClassCastException: class org.nlogo.core.Nobody$ cannot be cast to class org.nlogo.agent.Turtle (org.nlogo.core.Nobody$ and org.nlogo.agent.Turtle are in unnamed module of loader 'app')
 at org.nlogo.agent.AgentManagement.$anonfun$getOrCreateDummyLink$1(AgentManagement.scala:100)
 at scala.Option.getOrElse(Option.scala:189)
 at org.nlogo.agent.AgentManagement.getOrCreateDummyLink(AgentManagement.scala:100)
 at org.nlogo.agent.AgentManagement.getOrCreateDummyLink$(AgentManagement.scala:92)
 at org.nlogo.agent.World.getOrCreateDummyLink(World.scala:108)
 at org.nlogo.app.tools.AgentVarEditor.doAgentSwitch(AgentMonitorEditor.scala:358)
 at org.nlogo.app.tools.AgentVarEditor.action(AgentMonitorEditor.scala:326)
 at org.nlogo.app.tools.AgentVarEditor.keyPressed(AgentMonitorEditor.scala:236)
 at java.desktop/java.awt.Component.processKeyEvent(Unknown Source)
 at java.desktop/javax.swing.JComponent.processKeyEvent(Unknown Source)
 at java.desktop/java.awt.Component.processEvent(Unknown Source)
 at java.desktop/java.awt.Container.processEvent(Unknown Source)
 at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
 at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
 at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
 at java.desktop/java.awt.KeyboardFocusManager.redispatchEvent(Unknown Source)
 at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(Unknown Source)
 at java.desktop/java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(Unknown Source)
 at java.desktop/java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(Unknown Source)
 at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(Unknown Source)
 at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
 at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
 at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
 at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
 at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
 at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
 at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
 at java.base/java.security.AccessController.doPrivileged(Unknown Source)
 at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
 at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
 at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
 at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
 at java.base/java.security.AccessController.doPrivileged(Unknown Source)
 at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
 at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
 at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
 at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
 at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
 at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
 at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
 at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

NetLogo 6.4.0
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
OpenJDK 64-Bit Server VM 17.0.8.1 (BellSoft; 17.0.8.1+1-LTS)
operating system: Mac OS X 11.6.5 (x86_64 processor)
Scala version 2.12.18
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: test

04:07:13.826 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
04:07:13.620 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
04:07:13.415 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
04:07:13.214 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
04:07:13.013 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
04:07:12.812 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
04:07:12.572 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
04:07:12.366 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
04:07:12.165 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
04:07:11.961 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0

**Comment by LaCuneta** [comment] 2024-02-06 16:53
Thank you for reporting this issue and sorry you ran into it!  This appears to be a duplicate of #1999, entering a blank who number in the link monitor causes the exception.  Obviously that should be corrected, but hopefully you're able to work around the problem.  I'm closing this as a duplicate, but just let me know if I'm mistaken on the root cause and we'll re-open it to take another look.

**Closed by LaCuneta** 2024-02-06 16:53 UTC
