### ISSUE TITLE
Weird Error Occurs In the Middle Of Running My Connect 4 AI Program

### ISSUE THREAD

**Issue by stevenrakhmanchik** [NetLogo/NetLogo#1808] opened 2020-01-10 00:32 UTC
NetLogo is unable to supply you with more details about this error.  Please report the problem 
 at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the 
contents of this window into your report. 

java.lang.NullPointerException
 at java.util.LinkedList$ListItr.next(LinkedList.java:893)
 at org.nlogo.window.ViewManager.framesSkipped(ViewManager.java:40)
 at org.nlogo.window.GUIWorkspace.updateDisplay(GUIWorkspace.java:614)
 at org.nlogo.window.GUIWorkspace.breathe(GUIWorkspace.java:673)
 at org.nlogo.workspace.AbstractWorkspace.breathe(AbstractWorkspace.java:217)
 at org.nlogo.nvm.Context.comeUpForAir(Context.java:321)
 at org.nlogo.nvm.Context.runExclusive(Context.java:135)
 at org.nlogo.nvm.ExclusiveJob.run(ExclusiveJob.scala:39)
 at org.nlogo.nvm.Context.runExclusiveJob(Context.java:177)
 at org.nlogo.prim._asm_procedureplay_ask_14.perform(:1)
 at org.nlogo.nvm.Context.stepConcurrent(Context.java:107)
 at org.nlogo.nvm.ConcurrentJob.step(ConcurrentJob.scala:65)
 at org.nlogo.job.JobThread.runPrimaryJobs(JobThread.scala:133)
 at org.nlogo.job.JobThread.$anonfun$run$1(JobThread.scala:68)
 at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
 at scala.util.control.Exception$Catch.apply(Exception.scala:228)
 at org.nlogo.api.Exceptions$.handling(Exceptions.scala:41)
 at org.nlogo.job.JobThread.run(JobThread.scala:66)

NetLogo 6.1.1
main: org.nlogo.app.AppFrame
thread: JobThread
Java HotSpot(TM) 64-Bit Server VM 1.8.0_202 (Oracle Corporation; 1.8.0_202-b08)
operating system: Mac OS X 10.15 (x86_64 processor)
Scala version 2.12.8
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: connect4

07:16:55.283 SwitchedTabsEvent (org.nlogo.app.Tabs) AWT-EventQueue-0
07:16:55.201 RuntimeErrorEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
07:16:55.200 JobRemovedEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) JobThread
07:16:55.191 WidgetRemovedEvent (org.nlogo.app.tools.AgentVarEditor) AWT-EventQueue-0
07:16:55.191 RemoveJobEvent (org.nlogo.app.tools.AgentVarEditor) AWT-EventQueue-0
07:16:55.191 WidgetRemovedEvent (org.nlogo.app.tools.AgentVarEditor) AWT-EventQueue-0
07:16:55.191 RemoveJobEvent (org.nlogo.app.tools.AgentVarEditor) AWT-EventQueue-0
07:16:55.191 WidgetRemovedEvent (org.nlogo.app.tools.AgentVarEditor) AWT-EventQueue-0
07:16:55.190 RemoveJobEvent (org.nlogo.app.tools.AgentVarEditor) AWT-EventQueue-0
07:16:55.190 WidgetRemovedEvent (org.nlogo.app.tools.AgentVarEditor) AWT-EventQueue-0

**Comment by SethTisue** [comment] 2020-01-10 01:27
duplicate of #298

**Closed by SethTisue** 2020-01-10 01:27 UTC

**Comment by LaCuneta** [comment] 2020-01-13 15:18
@stevenrakhmanchik Thank you for reporting this issue and sorry you ran into it!  As Seth said this is likely a duplicate of a known issue.

As far as we're aware that known issue is intermittent and doesn't happen often.  If what you're seeing is the error happening frequently and you have steps that can cause it to occur reliably, posting those steps on issue #298 would be very appreciated.
